### ISSUE TITLE
[Lambda] Failing to invoke Node.js 6.10 function

### ISSUE THREAD

**Issue by aymericbeaumet** [atlassian/localstack#100]
Starting localstack with  the latest version from the `master` branch, I managed to create a lambda function with the Node.js AWS SDK, however I struggled to invoke it.

The zip archive is created with [adm-zip](https://github.com/cthackers/adm-zip), before being exported as a base64 string.

Required dependencies:
```bash
$ brew install n yarn && n 7.
$ yarn add aws-sdk adm-zip
```

_index.js_:
```js
#!/usr/bin/env node --harmony

const { Lambda } = require('aws-sdk');
const Zip = require('adm-zip');

(async function() {
  const lambda = new Lambda({
    endpoint: 'http://localhost:4574',
    region: 'eu-west-1',
  });
  await lambda.createFunction({
    FunctionName: 'testFunction',
    Runtime: 'nodejs6.10',
    Handler: 'index.handler',
    Code: {
      ZipFile: (() => {
        const zip = new Zip();
        zip.addFile('index.js', new Buffer(`
          exports.handler = function handler(event, context, callback) {
            return callback(null, event);
          };
        `));
        return zip.toBuffer();
      })(),
    },
    Role: 'testRole',
  }).promise();
  await lambda.invoke({
    FunctionName: 'testFunction',
    Payload: '{}',
  }).promise();
})().catch(console.error);
```
Localstack logs:
```
$ make docker-run
port_mappings=""; \
		mkdir -p /tmp/localstack; chmod -R 777 /tmp/localstack; \
		docker run -it  -e DEBUG= -e SERVICES= -e DATA_DIR= -e LAMBDA_EXECUTOR= -e KINESIS_ERROR_PROBABILITY= -p 4567-4581:4567-4581 -p 8080:8080 $port_mappings -v /tmp/localstack:/tmp/localstack -v /var/run/docker.sock:/var/run/docker.sock -e DOCKER_HOST="unix:///var/run/docker.sock" atlassianlabs/localstack
/usr/lib/python2.7/site-packages/supervisor/options.py:296: UserWarning: Supervisord is running as root and it is searching for its configuration file in default locations (including its current working directory); you probably want to specify a "-c" argument specifying an absolute path to a configuration file for improved security.
  'Supervisord is running as root and it is searching '
2017-05-10 13:15:24,256 CRIT Supervisor running as root (no user in config file)
2017-05-10 13:15:24,259 INFO supervisord started with pid 1
2017-05-10 13:15:25,266 INFO spawned: 'dashboard' with pid 7
2017-05-10 13:15:25,269 INFO spawned: 'infra' with pid 8
(. .venv/bin/activate; bin/localstack web --port=8080)
. .venv/bin/activate; exec localstack/mock/infra.py
Starting local dev environment. CTRL-C to quit.
 * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
 * Restarting with stat
Starting local Elasticsearch (port 4571)...
Starting mock ES service (port 4578)...
Starting mock S3 (port 4572)...
Starting mock SNS (port 4575)...
Starting mock SQS (port 4576)...
Starting mock API Gateway (port 4567)...
Starting mock DynamoDB (port 4569)...
Starting mock DynamoDB Streams service (port 4570)...
Starting mock Firehose service (port 4573)...
Starting mock Lambda service (port 4574)...
Starting mock Kinesis (port 4568)...
Starting mock Redshift (port 4577)...
Starting mock Route53 (port 4580)...
Starting mock SES (port 4579)...
Starting mock CloudFormation (port 4581)...
 * Debugger is active!
2017-05-10 13:15:26,524 INFO success: dashboard entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2017-05-10 13:15:26,524 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
 * Debugger PIN: 129-592-347
Ready.
docker run -e HOSTNAME="172.17.0.1" -e AWS_LAMBDA_EVENT_BODY="$AWS_LAMBDA_EVENT_BODY" -v "None":/var/task lambci/lambda:nodejs6.10 "index.handler"
ERROR: 'docker run -e HOSTNAME="172.17.0.1" -e AWS_LAMBDA_EVENT_BODY="$AWS_LAMBDA_EVENT_BODY" -v "None":/var/task lambci/lambda:nodejs6.10 "index.handler"': START RequestId: 157df854-2dd3-13e7-f2ec-ae02fede77b7 Version: $LATEST
Unable to import module 'index': Error
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
2017-05-10T13:18:16.347Z	157df854-2dd3-13e7-f2ec-ae02fede77b7	TypeError: awslambda.reportException is not a function

ERROR executing Lambda function: Traceback (most recent call last):
  File "/opt/code/localstack/localstack/mock/apis/lambda_api.py", line 174, in run_lambda
    result = run(cmd, env_vars={'AWS_LAMBDA_EVENT_BODY': event_string})
  File "/opt/code/localstack/localstack/utils/common.py", line 248, in run
    return do_run(cmd)
  File "/opt/code/localstack/localstack/utils/common.py", line 246, in do_run
    raise e
CalledProcessError: Command 'docker run -e HOSTNAME="172.17.0.1" -e AWS_LAMBDA_EVENT_BODY="$AWS_LAMBDA_EVENT_BODY" -v "None":/var/task lambci/lambda:nodejs6.10 "index.handler"' returned non-zero exit status 1
```

It seems the `index.js` cannot be found, though being in the lambda archive. This line `AWS_LAMBDA_EVENT_BODY="$AWS_LAMBDA_EVENT_BODY" -v "None":/var/task lambci/lambda:nodejs6.10 "index.handler"` leads [here](https://github.com/atlassian/localstack/blob/master/localstack/mock/apis/lambda_api.py#L208-L210), for some reasons the `lambda_cwd` is not defined, thus the lambdaci image cannot find the function.

**Comment by whummer** [comment]
Thanks for reporting. Not sure if it's related, but is this statement actually passing in the correct function name?
```
  await lambda.createFunction({
    FunctionName: lambda,
```
Can you give it a try and run this instead:
```
  await lambda.createFunction({
    FunctionName: 'testFunction',
```

**Comment by aymericbeaumet** [comment]
@whummer I simplified the code to isolate the issue, forgot that part 👍  It's not related

**Comment by whummer** [comment]
Can you try removing the base64 encoding part (The library should already take care of that).
Simply return the buffer:
```
return zip.toBuffer();
```
Also, note that the payload for the invocation has to be a valid JSON document (instead of `"testPayload"`).

**Comment by aymericbeaumet** [comment]
1/ I have tried to remove the base64 encoding, but this generates an internal error:

```
WARNING:localstack.mock.apis.lambda_api:Content of Lambda archive: total 8
drwxr-xr-x    4 root     root           136 May 11  2017 .
drwxrwxrwx   22 root     root           748 May 11  2017 ..
-rw-r--r--    1 root     root           161 May 11  2017 index.js
-rw-r--r--    1 root     root           217 May 11  2017 original_lambda_archive.zip

ERROR:lambda_mock:Exception on /2015-03-31/functions [POST]
Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/code/localstack/localstack/mock/apis/lambda_api.py", line 325, in create_function
    set_function_code(code, lambda_name)
  File "/opt/code/localstack/localstack/mock/apis/lambda_api.py", line 277, in set_function_code
    raise Exception('Unable to find handler script in Lambda archive.')
Exception: Unable to find handler script in Lambda archive.
WARNING:localstack.mock.apis.lambda_api:Content of Lambda archive: total 8
drwxr-xr-x    4 root     root           136 May 11  2017 .
drwxrwxrwx   23 root     root           782 May 11  2017 ..
-rw-r--r--    1 root     root           161 May 11  2017 index.js
-rw-r--r--    1 root     root           217 May 11  2017 original_lambda_archive.zip

ERROR:lambda_mock:Exception on /2015-03-31/functions [POST]
Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/code/localstack/localstack/mock/apis/lambda_api.py", line 325, in create_function
    set_function_code(code, lambda_name)
  File "/opt/code/localstack/localstack/mock/apis/lambda_api.py", line 277, in set_function_code
    raise Exception('Unable to find handler script in Lambda archive.')
Exception: Unable to find handler script in Lambda archive.
WARNING:localstack.mock.apis.lambda_api:Content of Lambda archive: total 8
drwxr-xr-x    4 root     root           136 May 11  2017 .
drwxrwxrwx   24 root     root           816 May 11  2017 ..
-rw-r--r--    1 root     root           161 May 11  2017 index.js
-rw-r--r--    1 root     root           217 May 11  2017 original_lambda_archive.zip

ERROR:lambda_mock:Exception on /2015-03-31/functions [POST]
Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/code/localstack/localstack/mock/apis/lambda_api.py", line 325, in create_function
    set_function_code(code, lambda_name)
  File "/opt/code/localstack/localstack/mock/apis/lambda_api.py", line 277, in set_function_code
    raise Exception('Unable to find handler script in Lambda archive.')
Exception: Unable to find handler script in Lambda archive.
WARNING:localstack.mock.apis.lambda_api:Content of Lambda archive: total 8
drwxr-xr-x    4 root     root           136 May 11  2017 .
drwxrwxrwx   25 root     root           850 May 11  2017 ..
-rw-r--r--    1 root     root           161 May 11  2017 index.js
-rw-r--r--    1 root     root           217 May 11  2017 original_lambda_archive.zip

ERROR:lambda_mock:Exception on /2015-03-31/functions [POST]
Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/code/localstack/localstack/mock/apis/lambda_api.py", line 325, in create_function
    set_function_code(code, lambda_name)
  File "/opt/code/localstack/localstack/mock/apis/lambda_api.py", line 277, in set_function_code
    raise Exception('Unable to find handler script in Lambda archive.')
Exception: Unable to find handler script in Lambda archive.
ERROR: Unable to find handler script in Lambda archive.
ERROR: Unable to find handler script in Lambda archive.
ERROR: Unable to find handler script in Lambda archive.
ERROR: Unable to find handler script in Lambda archive.
```

2/ Passing an stringified object instead of a `testPayload` still produces the same error. As expected I think, as this would make the lambda fail when invoked (by lambdaci), not before.

Localstack fails to mount the extracted lambda.zip into lambci, the `"None"` here: `-v "None":/var/task lambci/lambda:nodejs6.10` causes Docker to fail to mount the volume containing the lambda code, hence failing to import the entrypoint (`Unable to import module 'index': Error`)

**Comment by whummer** [comment]
Which version of the Docker image are you using? I can actually run your script with the following image version:
```
$ docker images | grep localstack | grep latest
atlassianlabs/localstack                            latest                                                          96c17589bc26        17 hours ago         1.06 GB
```
If you have a different image, can you try to pull the latest version:
```
docker pull atlassianlabs/localstack:0.4.2
docker pull atlassianlabs/localstack
```

**Comment by aymericbeaumet** [comment]
I've been trying on the latest master with `make docker-run`.

When I try with `docker run --rm -it -p 4567-4578:4567-4578 atlassianlabs/localstack:latest` I get the following error:

```
WARNING:localstack.mock.apis.lambda_api:Error executing Lambda function: Unable to find executor for Lambda function "testFunction". Note that non-Python Lambdas require LAMBDA_EXECUTOR=docker Traceback (most recent call last):
  File "/opt/code/localstack/localstack/mock/apis/lambda_api.py", line 219, in run_lambda
    result = func(event, context)
  File "/opt/code/localstack/localstack/mock/apis/lambda_api.py", line 286, in generic_handler
    'Note that non-Python Lambdas require LAMBDA_EXECUTOR=docker') % lambda_name)
Exception: Unable to find executor for Lambda function "testFunction". Note that non-Python Lambdas require LAMBDA_EXECUTOR=docker
```

This error persists even when I specify the lambda executor trough the environment.

**Comment by whummer** [comment]
That output looks better, in fact I believe you are now only missing the volume mount for `/var/run/docker.sock`. Running with `make docker-run` is actually the recommended way, we just need to make sure that the command uses the latest version of the `atlassianlabs/localstack` image.

When you run `docker images | grep localstack | grep latest`, does it print the right image ID (`96c17589bc26`)?

Can you please try again with the following:
```
docker pull atlassianlabs/localstack:0.4.2
docker pull atlassianlabs/localstack:latest
docker pull atlassianlabs/localstack
make docker-run
```

If your test still does not work afterwards, then we need more debug info (please post the output for each of these commands):
```
ls -la /var/run/docker.sock
docker -v
uname -a
ls -la /var/run/docker.sock
docker run -it --entrypoint= atlassianlabs/localstack ping -c 1 -t 1 172.17.0.1
docker run -it --entrypoint= -v /var/run/docker.sock:/var/run/docker.sock -e DOCKER_HOST="unix:///var/run/docker.sock" atlassianlabs/localstack ls -la /var/run/docker.sock
docker run -it --entrypoint= -v /var/run/docker.sock:/var/run/docker.sock -e DOCKER_HOST="unix:///var/run/docker.sock" atlassianlabs/localstack docker ps
```

Apologies for the back and forth, but we should be able to get that fixed soon (hopefully). Thanks

**Comment by aymericbeaumet** [comment]
I appear to have the latest version:

```bash
$ docker images | grep localstack | grep latest
atlassianlabs/localstack   latest              96c17589bc26        20 hours ago        1.06 GB
```

I tried again with `make docker-run` and it works 👍 

I got confused by the readme.md: regarding the [Running in Docker section](https://github.com/atlassian/localstack#running-in-docker). It seems `docker run` is not enough to have a 100% working localstack (maybe it should be removed?).

Thanks for the help @whummer!

**Comment by aymericbeaumet** [comment]
It's weird though that `make docker-run` relies on an external source? I would expect it to build the image locally.

Also the `docker run` from the readme should be removed in favor of https://github.com/atlassian/localstack/pull/86/files

**Comment by whummer** [comment]
Glad it works now. The `docker-compose.yml` file has now been added, documentation is updated as well. Cheers

**Comment by aymericbeaumet** [comment]
Awesome @whummer! Keep up the good work

**Comment by mvayngrib** [comment]
i'm getting this error (`Unable to find executor for Lambda function`) when using serverless to deploy to localstack (see [demo repo](https://github.com/mvayngrib/localstack-test)):

(see first i'm listing the functions)

```sh
$ aws lambda list-functions --endpoint-url http://localhost:4574
{
    "Functions": [
        {
            "Version": "$LATEST", 
            "FunctionName": "localstack-test-dev-failtest", 
            "FunctionArn": "arn:aws:lambda:us-east-1:000000000000:function:localstack-test-dev-failtest", 
            "Handler": "failtest.handler", 
            "Timeout": 60, 
            "Runtime": "nodejs6.10"
        }, 
        {
            "Version": "$LATEST", 
            "FunctionName": "localstack-test-dev-hello", 
            "FunctionArn": "arn:aws:lambda:us-east-1:000000000000:function:localstack-test-dev-hello", 
            "Handler": "handler.hello", 
            "Timeout": 60, 
            "Runtime": "nodejs6.10"
        }, 
        {
            "Version": "$LATEST", 
            "FunctionName": "localstack-test-dev-invoker", 
            "FunctionArn": "arn:aws:lambda:us-east-1:000000000000:function:localstack-test-dev-invoker", 
            "Handler": "invoker.handler", 
            "Timeout": 60, 
            "Runtime": "nodejs6.10"
        }
    ]
}
~/Code/localstack-serverless on master
$ aws lambda invoke --endpoint-url http://localhost:4574 --function-name localstack-test-dev-hello --payload '{}' out.txt

An error occurred (Exception) when calling the Invoke operation: Error executing Lambda function: Unable to find executor for Lambda function "localstack-test-dev-hello". Note that non-Python Lambdas require LAMBDA_EXECUTOR=docker Traceback (most recent call last):
  File "/opt/code/localstack/localstack/mock/apis/lambda_api.py", line 286, in run_lambda
    process.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/code/localstack/localstack/mock/apis/lambda_api.py", line 282, in do_execute
    result = func(event, context)
  File "/opt/code/localstack/localstack/mock/apis/lambda_api.py", line 348, in generic_handler
    'Note that non-Python Lambdas require LAMBDA_EXECUTOR=docker') % lambda_name)
Exception: Unable to find executor for Lambda function "localstack-test-dev-hello". Note that non-Python Lambdas require LAMBDA_EXECUTOR=docker
```

**Comment by aymericbeaumet** [comment]
Please create your own issue :+1:, will try to give you some tips there ;)

**Comment by mvayngrib** [comment]
@aymericbeaumet no problem, opened #126 Thanks!

**Comment by sanjeevsiva17** [comment]
> i'm getting this error (`Unable to find executor for Lambda function`) when using serverless to deploy to localstack (see [demo repo](https://github.com/mvayngrib/localstack-test)):
> 
> (see first i'm listing the functions)
> 
> ```shell
> $ aws lambda list-functions --endpoint-url http://localhost:4574
> {
>     "Functions": [
>         {
>             "Version": "$LATEST", 
>             "FunctionName": "localstack-test-dev-failtest", 
>             "FunctionArn": "arn:aws:lambda:us-east-1:000000000000:function:localstack-test-dev-failtest", 
>             "Handler": "failtest.handler", 
>             "Timeout": 60, 
>             "Runtime": "nodejs6.10"
>         }, 
>         {
>             "Version": "$LATEST", 
>             "FunctionName": "localstack-test-dev-hello", 
>             "FunctionArn": "arn:aws:lambda:us-east-1:000000000000:function:localstack-test-dev-hello", 
>             "Handler": "handler.hello", 
>             "Timeout": 60, 
>             "Runtime": "nodejs6.10"
>         }, 
>         {
>             "Version": "$LATEST", 
>             "FunctionName": "localstack-test-dev-invoker", 
>             "FunctionArn": "arn:aws:lambda:us-east-1:000000000000:function:localstack-test-dev-invoker", 
>             "Handler": "invoker.handler", 
>             "Timeout": 60, 
>             "Runtime": "nodejs6.10"
>         }
>     ]
> }
> ~/Code/localstack-serverless on master
> $ aws lambda invoke --endpoint-url http://localhost:4574 --function-name localstack-test-dev-hello --payload '{}' out.txt
> 
> An error occurred (Exception) when calling the Invoke operation: Error executing Lambda function: Unable to find executor for Lambda function "localstack-test-dev-hello". Note that non-Python Lambdas require LAMBDA_EXECUTOR=docker Traceback (most recent call last):
>   File "/opt/code/localstack/localstack/mock/apis/lambda_api.py", line 286, in run_lambda
>     process.run()
>   File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
>     self._target(*self._args, **self._kwargs)
>   File "/opt/code/localstack/localstack/mock/apis/lambda_api.py", line 282, in do_execute
>     result = func(event, context)
>   File "/opt/code/localstack/localstack/mock/apis/lambda_api.py", line 348, in generic_handler
>     'Note that non-Python Lambdas require LAMBDA_EXECUTOR=docker') % lambda_name)
> Exception: Unable to find executor for Lambda function "localstack-test-dev-hello". Note that non-Python Lambdas require LAMBDA_EXECUTOR=docker
> ```

TMPDIR=/private$TMPDIR LAMBDA_EXECUTOR=docker localstack start --docker

Try running localstack like this !
