### ISSUE TITLE
Objects Disappearing + Logging "ERROR checking state of local environment. "

### ISSUE THREAD

**Issue by cphoover** [atlassian/localstack#104]
I am able to create objects... for example:

```
aws --endpoint-url=http://localhost:4576 sqs create-queue --queue-name=compass-corvisa  --region=us-east-1
{
    "QueueUrl": "http://localhost:4576/123456789012/compass-corvisa"
}
```
Works. But then a few seconds later I run: 

```
 aws --endpoint-url=http://localhost:4576 sqs list-queues --region=us-east-1
```
and I get no output.

I looked at the docker logs from `docker run -it -p 4567-4580:4567-4580 -p 8080:8080 atlassianlabs/locals` and I get:

```
ERROR checking state of local environment (after some retries): Traceback (most recent call last):
  File "localstack/mock/infra.py", line 275, in check_infra
    check_infra_elasticsearch(expect_shutdown=expect_shutdown, print_error=print_error)
  File "localstack/mock/infra.py", line 258, in check_infra_elasticsearch
    assert isinstance(out, basestring)
AssertionError

Traceback (most recent call last):
  File "localstack/mock/infra.py", line 384, in <module>
    start_infra()
  File "localstack/mock/infra.py", line 360, in start_infra
    check_infra(apis=apis)
  File "localstack/mock/infra.py", line 283, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "localstack/mock/infra.py", line 283, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "localstack/mock/infra.py", line 283, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "localstack/mock/infra.py", line 283, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "localstack/mock/infra.py", line 283, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "localstack/mock/infra.py", line 283, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "localstack/mock/infra.py", line 283, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "localstack/mock/infra.py", line 281, in check_infra
    raise e
AssertionError
```

**Comment by cphoover** [comment]
I'm using the docker TAG: latest

**Comment by whummer** [comment]
Thanks for reporting. Can you please paste the image ID you are using:
```
docker image inspect atlassianlabs/localstack | grep Id
```

Can you please try running LocalStack using this command:
```
make docker-run
```

.. and then paste the full log output. The relevant part in particular is the output from Elasticsearch. On my machine it looks like this:
```
...
[2017-05-13T12:47:31,141][INFO ][o.e.n.Node               ] [] initializing ...
[2017-05-13T12:47:31,297][INFO ][o.e.e.NodeEnvironment    ] [BfPONJK] using [1] data paths, mounts [[/ (none)]], net usable_space [12.6gb], net total_space [59gb], spins? [possibly], types [aufs]
[2017-05-13T12:47:31,298][INFO ][o.e.e.NodeEnvironment    ] [BfPONJK] heap size [483.3mb], compressed ordinary object pointers [true]
[2017-05-13T12:47:31,300][INFO ][o.e.n.Node               ] node name [BfPONJK] derived from node ID [BfPONJK-RXO-UuzXE0B9lQ]; set [node.name] to override
[2017-05-13T12:47:31,300][INFO ][o.e.n.Node               ] version[5.3.0], pid[54], build[3adb13b/2017-03-23T03:31:50.652Z], OS[Linux/4.9.13-moby/amd64], JVM[Oracle Corporation/OpenJDK 64-Bit Server VM/1.8.0_121/25.121-b13]
[2017-05-13T12:47:32,148][INFO ][o.e.p.PluginsService     ] [BfPONJK] loaded module [aggs-matrix-stats]
[2017-05-13T12:47:32,150][INFO ][o.e.p.PluginsService     ] [BfPONJK] loaded module [ingest-common]
[2017-05-13T12:47:32,150][INFO ][o.e.p.PluginsService     ] [BfPONJK] loaded module [lang-expression]
[2017-05-13T12:47:32,150][INFO ][o.e.p.PluginsService     ] [BfPONJK] loaded module [lang-groovy]
[2017-05-13T12:47:32,151][INFO ][o.e.p.PluginsService     ] [BfPONJK] loaded module [lang-mustache]
[2017-05-13T12:47:32,151][INFO ][o.e.p.PluginsService     ] [BfPONJK] loaded module [lang-painless]
[2017-05-13T12:47:32,151][INFO ][o.e.p.PluginsService     ] [BfPONJK] loaded module [percolator]
[2017-05-13T12:47:32,151][INFO ][o.e.p.PluginsService     ] [BfPONJK] loaded module [reindex]
[2017-05-13T12:47:32,151][INFO ][o.e.p.PluginsService     ] [BfPONJK] loaded module [transport-netty3]
[2017-05-13T12:47:32,151][INFO ][o.e.p.PluginsService     ] [BfPONJK] loaded module [transport-netty4]
[2017-05-13T12:47:32,152][INFO ][o.e.p.PluginsService     ] [BfPONJK] no plugins loaded
[2017-05-13T12:47:34,557][INFO ][o.e.n.Node               ] initialized
[2017-05-13T12:47:34,557][INFO ][o.e.n.Node               ] [BfPONJK] starting ...
[2017-05-13T12:47:34,673][WARN ][i.n.u.i.MacAddressUtil   ] Failed to find a usable hardware address from the network interfaces; using random bytes: 14:da:49:10:7d:9e:1d:a3
[2017-05-13T12:47:34,751][INFO ][o.e.t.TransportService   ] [BfPONJK] publish_address {127.0.0.1:9300}, bound_addresses {[::1]:9300}, {127.0.0.1:9300}
[2017-05-13T12:47:34,762][WARN ][o.e.b.BootstrapChecks    ] [BfPONJK] initial heap size [209715200] not equal to maximum heap size [524288000]; this can cause resize pauses and prevents mlockall from locking the entire heap
[2017-05-13T12:47:37,859][INFO ][o.e.c.s.ClusterService   ] [BfPONJK] new_master {BfPONJK}{BfPONJK-RXO-UuzXE0B9lQ}{hzPSYmWkQf2uoSJVlDLkSA}{127.0.0.1}{127.0.0.1:9300}, reason: zen-disco-elected-as-master ([0] nodes joined)
[2017-05-13T12:47:37,904][INFO ][o.e.h.n.Netty4HttpServerTransport] [BfPONJK] publish_address {127.0.0.1:4587}, bound_addresses {[::1]:4587}, {127.0.0.1:4587}
[2017-05-13T12:47:37,909][INFO ][o.e.n.Node               ] [BfPONJK] started
[2017-05-13T12:47:37,959][INFO ][o.e.g.GatewayService     ] [BfPONJK] recovered [0] indices into cluster_state
Ready.
```
Thanks

**Comment by whummer** [comment]
Any update on this issue @cphoover? Have you tried pulling the latest Docker image? Thanks

**Comment by cphoover** [comment]
It seems removing the image from docker and re pulling fixed the issue
