### ISSUE TITLE
unable to find executor for Lambda function (serverless-based deployment)

### ISSUE THREAD

**Issue by mvayngrib** [atlassian/localstack#126]
moving issue here from #100 

i'm getting this error (`Unable to find executor for Lambda function`) when using serverless to deploy to localstack (see [demo repo](https://github.com/mvayngrib/localstack-test)):

(see first i'm listing the functions)

```sh
$ aws lambda list-functions --endpoint-url http://localhost:4574
{
    "Functions": [
        {
            "Version": "$LATEST", 
            "FunctionName": "localstack-test-dev-failtest", 
            "FunctionArn": "arn:aws:lambda:us-east-1:000000000000:function:localstack-test-dev-failtest", 
            "Handler": "failtest.handler", 
            "Timeout": 60, 
            "Runtime": "nodejs6.10"
        }, 
        {
            "Version": "$LATEST", 
            "FunctionName": "localstack-test-dev-hello", 
            "FunctionArn": "arn:aws:lambda:us-east-1:000000000000:function:localstack-test-dev-hello", 
            "Handler": "handler.hello", 
            "Timeout": 60, 
            "Runtime": "nodejs6.10"
        }, 
        {
            "Version": "$LATEST", 
            "FunctionName": "localstack-test-dev-invoker", 
            "FunctionArn": "arn:aws:lambda:us-east-1:000000000000:function:localstack-test-dev-invoker", 
            "Handler": "invoker.handler", 
            "Timeout": 60, 
            "Runtime": "nodejs6.10"
        }
    ]
}
~/Code/localstack-serverless on master
$ aws lambda invoke --endpoint-url http://localhost:4574 --function-name localstack-test-dev-hello --payload '{}' out.txt

An error occurred (Exception) when calling the Invoke operation: Error executing Lambda function: Unable to find executor for Lambda function "localstack-test-dev-hello". Note that non-Python Lambdas require LAMBDA_EXECUTOR=docker Traceback (most recent call last):
  File "/opt/code/localstack/localstack/mock/apis/lambda_api.py", line 286, in run_lambda
    process.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/code/localstack/localstack/mock/apis/lambda_api.py", line 282, in do_execute
    result = func(event, context)
  File "/opt/code/localstack/localstack/mock/apis/lambda_api.py", line 348, in generic_handler
    'Note that non-Python Lambdas require LAMBDA_EXECUTOR=docker') % lambda_name)
Exception: Unable to find executor for Lambda function "localstack-test-dev-hello". Note that non-Python Lambdas require LAMBDA_EXECUTOR=docker
```

**Comment by whummer** [comment]
@mvayngrib I cannot find a serverless config yaml file in that repo - did you push your changes? From the error message it seems that LocalStack cannot execute your Lambda. How do you run LocalStack - are you using `docker-compose`, oder `make docker-run`?

**Comment by mvayngrib** [comment]
@whummer haha crap, my bad. Pushed now. I'm using `make docker-run`

**Comment by whummer** [comment]
Interesting, works for me:
```
$ aws lambda invoke --endpoint-url http://localhost:4574 --function-name localstack-test-dev-hello --payload '{}' out.txt
{
    "StatusCode": 200
}
```

Let's do some debugging (please post relevant output):
```
image_id=`docker ps | grep localstack | awk '{print $1;}'`
docker exec $image_id which docker
docker exec $image_id docker -v
docker exec $image_id docker images | wc -l
docker exec $image_id ls -la /var/run/docker.sock
ls -la /var/run/docker.sock
```

**Comment by mvayngrib** [comment]
@whummer see output below. Is there a typo in the 4th line?
```sh
~/Code/localstack-test on master*
$ image_id=`docker ps | grep localstack | awk '{print $1;}'`
~/Code/localstack-test on master*
$ docker exec $image_id which docker
/usr/bin/docker
~/Code/localstack-test on master*
$ docker exec $image_id docker -v
Docker version 1.12.6, build v1.12.6
~/Code/localstack-test on master*
$ docker exec $image_id docker images | wc -l
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
0
~/Code/localstack-test on master*
$ docker exec $image_id ls -la /var/run/docker.sock
srw-rw----    1 nobody   nobody           0 Jun 13 12:58 /var/run/docker.sock
~/Code/localstack-test on master*
$ ls -la /var/run/docker.sock
lrwxr-xr-x 1 root daemon 64 Jun 13 08:57 /var/run/docker.sock -> /Users/tenaciousmv/Library/Containers/com.docker.docker/Data/s60
```

**Comment by whummer** [comment]
No, not a typo, that's exactly the root cause of the problem. You should be able to run docker commands (e.g., `docker images`) from within the docker container.

What about this?
```
docker exec $image_id bash -c 'echo $DOCKER_HOST'
```
If the above command returns an empty line, please try:
```
docker exec $image_id bash -c 'DOCKER_HOST=unix:///var/run/docker.sock docker images'
```
Assuming that this still does not work, next:
```
ls -la /Users/tenaciousmv/Library/Containers/com.docker.docker/Data/s60
docker exec $image_id bash -c 'apk add --update socat'
docker exec $image_id socat -u EXEC:'echo 123' UNIX:/var/run/docker.sock
```

**Comment by mvayngrib** [comment]
oh didn't know you could do that

```sh
$ docker exec $image_id bash -c 'echo $DOCKER_HOST'
unix:///var/run/docker.sock
```

**Comment by whummer** [comment]
Ok, so that works. Can you run the last three commands I posted above?

**Comment by whummer** [comment]
Looks like there is an issue here with the file permissions of `/var/run/docker.sock` - the user that docker is running under is unable to access that UNIX socket.

I vaguely recall a similar case of another user who had to re-create the docker.sock link in his local filesystem, or something similar. But I'm reluctant to provide any commands for remote debugging/fixing here, as these changes might have side-effects to your local Docker installation. :/ 

Not sure what would be the best way moving forward from here. Maybe a search on google/stackoverflow to figure out if any other user had a similar issue before? It *should* be a pretty common use case - the search terms would be something along the lines of "running `docker` commands from within a Docker container on MacOS by mounting the docker UNIX socket into the container".

**Comment by mvayngrib** [comment]
@whummer you're right! It seems I added this to my Docker for Mac settings (to prevent docker container root from becoming host root):

```json
{
  "userns-remap" : "default",
  "experimental" : true
}
```

removing it gets me farther...though i feel a little naked

running `docker images` from inside the container shell now works (yay!). But invoking my function now hangs, with no additional log output in the shell where I ran `make docker-run`. After a few minutes it printed:

```sh
HTTPConnectionPool(host='localhost', port=4574): Read timed out. (read timeout=60)
```

 Do you have another diagnostic up your sleeve? :)

**Comment by mvayngrib** [comment]
@whummer i take it back, after restarting things once more, it no longer times out. Not sure what was wrong before. Thanks!

**Comment by whummer** [comment]
Awesome, I'm glad it's working now. Feel free to re-open this issue if there are any other problems.

**Comment by hpatoio** [comment]
For people coming to this issue with the same problem. This config works for me;

```
  localstack: 
    image: localstack/localstack
    ports:
      - "4566:4566"
      - "8080:8080"
    volumes:
      - ./aws:/docker-entrypoint-initaws.d
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - SERVICES=sqs,lambda
      - LAMBDA_EXECUTOR=docker
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_DEFAULT_REGION=eu-west-1
      - DEBUG=1
      - PORT_WEB_UI=8080
    networks: 
      - default
    privileged: true
```
