### ISSUE TITLE
Dashboard error on simple docker set up on versions 0.5.3.1, 0.5.4 and 0.5.5

### ISSUE THREAD

**Issue by chrisburrell** [atlassian/localstack#139]
Hi

I'm trying to see the dashboard (and perhaps mis-understand what it's supposed to do) but on hitting the url (localhost:8080) i get a screen saying: "An error has occurred, could not load data from the service." The Refresh Graph button gives me the same error.

The logs show a python stacktrace:
```
172.17.0.1 - - [29/Jun/2017 17:13:31] "POST /graph HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/code/localstack/localstack/dashboard/api.py", line 36, in get_graph
    graph = infra.get_graph(name_filter=data['nameFilter'], env=env)
  File "/opt/code/localstack/localstack/dashboard/infra.py", line 425, in get_graph
    domains = get_elasticsearch_domains(name_filter, pool=pool, env=env)
  File "/opt/code/localstack/localstack/dashboard/infra.py", line 291, in get_elasticsearch_domains
    out = cmd_es('list-domain-names', env)
  File "/opt/code/localstack/localstack/dashboard/infra.py", line 51, in cmd_es
    return run_aws_cmd('es', cmd_params, env)
  File "/opt/code/localstack/localstack/dashboard/infra.py", line 42, in run_aws_cmd
    cmd = '%s %s' % (aws_cmd(service, env), cmd_params)
  File "/opt/code/localstack/localstack/dashboard/infra.py", line 86, in aws_cmd
    if not is_port_open(endpoint_url):
  File "/opt/code/localstack/localstack/utils/common.py", line 168, in is_port_open
    port = url.port
  File "/usr/lib/python2.7/urlparse.py", line 113, in port
    port = int(port, 10)
ValueError: invalid literal for int() with base 10: 'None'
```

**Comment by whummer** [comment]
Thanks for reporting. This is fixed in commit 9073a90e4d15d6d38de0d7ea6dd85ac2b50524d4 . Docker image version `0.5.5` has been updated. Please re-open this ticket if the problem persists. Thanks
