### ISSUE TITLE
brew install failed

### ISSUE THREAD

**Issue by zhoub** [atlassian/localstack#141]
Hi,

I tried to install the localstack though the brew and pip, but failed at handling the dependencies, is there anybody know this ? Thanks very much !

```
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 861, in emit
    msg = self.format(record)
  File "/usr/local/lib/python2.7/site-packages/pip/utils/logging.py", line 106, in format
    msg = logging.StreamHandler.format(self, record)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 734, in format
    return fmt.format(record)
  File "/usr/local/lib/python2.7/site-packages/pip/utils/logging.py", line 52, in format
    formatted = logging.Formatter.format(self, record)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 465, in format
    record.message = record.getMessage()
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 329, in getMessage
    msg = msg % self.args
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_install.py", line 251, in __str__
    s += ' in %s' % display_path(self.satisfied_by.location)
  File "/usr/local/lib/python2.7/site-packages/pip/utils/__init__.py", line 127, in display_path
    if path.startswith(os.getcwd() + os.path.sep):
OSError: [Errno 2] No such file or directory
Logged from file req_set.py, line 496
Collecting itsdangerous>=0.21 (from flask==0.10.1->localstack)
```

**Comment by zhoub** [comment]
Sorry my fault, I forgot sudo and put maven to PATH :)

**Comment by whummer** [comment]
Hi, I'm glad you were able to solve it, but can you please provide some details. How did you install LocalStack via brew? Please note that using `sudo` is generally **not** recommended.
