### ISSUE TITLE
make install-web command fails

### ISSUE THREAD

**Issue by arun-gupta** [atlassian/localstack#35]
`make install-web` command to install the Web Dashboard fails with the following error:

```
localstack > make install-web
(cd localstack/dashboard/web && (test ! -e package.json || npm install))
npm WARN deprecated showdown@0.3.1: IMPORTANT hotfix
npm WARN deprecated minimatch@3.0.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated ignore@2.2.19: several bugs fixed in v3.2.1
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@1.0.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated graceful-fs@2.0.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.

> v8-debug@0.7.7 preinstall /Users/arungupta/workspaces/localstack/localstack/dashboard/web/node_modules/.staging/v8-debug-6f45980d
> node -e 'process.exit(0)'


> v8-profiler@5.6.5 preinstall /Users/arungupta/workspaces/localstack/localstack/dashboard/web/node_modules/.staging/v8-profiler-c472ac90
> node -e 'process.exit(0)'

npm WARN prefer global coffee-script@1.12.4 should be installed with -g
npm WARN prefer global marked@0.3.6 should be installed with -g
npm WARN prefer global jsonlint@1.6.2 should be installed with -g
npm WARN prefer global node-inspector@0.12.8 should be installed with -g

> fsevents@1.1.1 install /Users/arungupta/workspaces/localstack/localstack/dashboard/web/node_modules/fsevents
> node install

[fsevents] Success: "/Users/arungupta/workspaces/localstack/localstack/dashboard/web/node_modules/fsevents/lib/binding/Release/node-v51-darwin-x64/fse.node" is installed via remote

> v8-debug@0.7.7 install /Users/arungupta/workspaces/localstack/localstack/dashboard/web/node_modules/v8-debug
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(404): https://node-inspector.s3.amazonaws.com/debug/v0.7.7/node-v51-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for v8-debug@0.7.7 and node@7.3.0 (node-v51 ABI) (falling back to source compile with node-gyp) 
  CXX(target) Release/obj.target/debug/src/debug.o
../src/debug.cc:38:27: error: too few arguments to function call, expected at least 2, have 1
        v8::Debug::Call(fn);
        ~~~~~~~~~~~~~~~   ^
/Users/arungupta/.node-gyp/7.3.0/include/node/v8-debug.h:198:3: note: 'Call' declared here
  static MaybeLocal<Value> Call(Local<Context> context,
  ^
../src/debug.cc:46:61: error: too few arguments to function call, single argument 'isolate' was not specified
        Isolate* debug_isolate = v8::Debug::GetDebugContext()->GetIsolate();
                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
/Users/arungupta/.node-gyp/7.3.0/include/node/v8-debug.h:248:3: note: 'GetDebugContext' declared here
  static Local<Context> GetDebugContext(Isolate* isolate);
  ^
../src/debug.cc:61:67: error: too few arguments to function call, single argument 'isolate' was not specified
        Local<Context> debug_context = v8::Debug::GetDebugContext();
                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
/Users/arungupta/.node-gyp/7.3.0/include/node/v8-debug.h:248:3: note: 'GetDebugContext' declared here
  static Local<Context> GetDebugContext(Isolate* isolate);
  ^
../src/debug.cc:66:54: error: too few arguments to function call, single argument 'isolate' was not specified
          debug_context = v8::Debug::GetDebugContext();
                          ~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
/Users/arungupta/.node-gyp/7.3.0/include/node/v8-debug.h:248:3: note: 'GetDebugContext' declared here
  static Local<Context> GetDebugContext(Isolate* isolate);
  ^
4 errors generated.
make[1]: *** [Release/obj.target/debug/src/debug.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 16.4.0
gyp ERR! command "/usr/local/Cellar/node/7.3.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/arungupta/workspaces/localstack/localstack/dashboard/web/node_modules/v8-debug/build/debug/v0.7.7/node-v51-darwin-x64/debug.node" "--module_name=debug" "--module_path=/Users/arungupta/workspaces/localstack/localstack/dashboard/web/node_modules/v8-debug/build/debug/v0.7.7/node-v51-darwin-x64"
gyp ERR! cwd /Users/arungupta/workspaces/localstack/localstack/dashboard/web/node_modules/v8-debug
gyp ERR! node -v v7.3.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp build --fallback-to-build --module=/Users/arungupta/workspaces/localstack/localstack/dashboard/web/node_modules/v8-debug/build/debug/v0.7.7/node-v51-darwin-x64/debug.node --module_name=debug --module_path=/Users/arungupta/workspaces/localstack/localstack/dashboard/web/node_modules/v8-debug/build/debug/v0.7.7/node-v51-darwin-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/arungupta/workspaces/localstack/localstack/dashboard/web/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:885:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
node-pre-gyp ERR! System Darwin 16.4.0
node-pre-gyp ERR! command "/usr/local/Cellar/node/7.3.0/bin/node" "/Users/arungupta/workspaces/localstack/localstack/dashboard/web/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/arungupta/workspaces/localstack/localstack/dashboard/web/node_modules/v8-debug
node-pre-gyp ERR! node -v v7.3.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.34
node-pre-gyp ERR! not ok 
Failed to execute 'node-gyp build --fallback-to-build --module=/Users/arungupta/workspaces/localstack/localstack/dashboard/web/node_modules/v8-debug/build/debug/v0.7.7/node-v51-darwin-x64/debug.node --module_name=debug --module_path=/Users/arungupta/workspaces/localstack/localstack/dashboard/web/node_modules/v8-debug/build/debug/v0.7.7/node-v51-darwin-x64' (1)

> v8-profiler@5.6.5 install /Users/arungupta/workspaces/localstack/localstack/dashboard/web/node_modules/v8-profiler
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(404): https://node-inspector.s3.amazonaws.com/profiler/v5.6.5/node-v51-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for v8-profiler@5.6.5 and node@7.3.0 (node-v51 ABI) (falling back to source compile with node-gyp) 
  CXX(target) Release/obj.target/profiler/src/profiler.o
  CXX(target) Release/obj.target/profiler/src/cpu_profiler.o
  CXX(target) Release/obj.target/profiler/src/cpu_profile.o
  CXX(target) Release/obj.target/profiler/src/cpu_profile_node.o
  CXX(target) Release/obj.target/profiler/src/heap_profiler.o
../src/heap_profiler.cc:35:18: warning: 'TryCatch' is deprecated [-Wdeprecated-declarations]
        TryCatch try_catch;
                 ^
/Users/arungupta/.node-gyp/7.3.0/include/node/v8.h:7015:40: note: 'TryCatch' has been explicitly marked deprecated here
  V8_DEPRECATED("Use isolate version", TryCatch());
                                       ^
1 warning generated.
  CXX(target) Release/obj.target/profiler/src/heap_snapshot.o
../src/heap_snapshot.cc:46:46: error: no member named 'GetHiddenValue' in 'v8::Object'
      info.GetReturnValue().Set(info.This()->GetHiddenValue(__root));
                                ~~~~~~~~~~~  ^
../src/heap_snapshot.cc:50:20: error: no member named 'SetHiddenValue' in 'v8::Object'
      info.This()->SetHiddenValue(__root, _root);
      ~~~~~~~~~~~  ^
2 errors generated.
make[1]: *** [Release/obj.target/profiler/src/heap_snapshot.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 16.4.0
gyp ERR! command "/usr/local/Cellar/node/7.3.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/arungupta/workspaces/localstack/localstack/dashboard/web/node_modules/v8-profiler/build/profiler/v5.6.5/node-v51-darwin-x64/profiler.node" "--module_name=profiler" "--module_path=/Users/arungupta/workspaces/localstack/localstack/dashboard/web/node_modules/v8-profiler/build/profiler/v5.6.5/node-v51-darwin-x64"
gyp ERR! cwd /Users/arungupta/workspaces/localstack/localstack/dashboard/web/node_modules/v8-profiler
gyp ERR! node -v v7.3.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp build --fallback-to-build --module=/Users/arungupta/workspaces/localstack/localstack/dashboard/web/node_modules/v8-profiler/build/profiler/v5.6.5/node-v51-darwin-x64/profiler.node --module_name=profiler --module_path=/Users/arungupta/workspaces/localstack/localstack/dashboard/web/node_modules/v8-profiler/build/profiler/v5.6.5/node-v51-darwin-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/arungupta/workspaces/localstack/localstack/dashboard/web/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:885:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
node-pre-gyp ERR! System Darwin 16.4.0
node-pre-gyp ERR! command "/usr/local/Cellar/node/7.3.0/bin/node" "/Users/arungupta/workspaces/localstack/localstack/dashboard/web/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/arungupta/workspaces/localstack/localstack/dashboard/web/node_modules/v8-profiler
node-pre-gyp ERR! node -v v7.3.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.34
node-pre-gyp ERR! not ok 
Failed to execute 'node-gyp build --fallback-to-build --module=/Users/arungupta/workspaces/localstack/localstack/dashboard/web/node_modules/v8-profiler/build/profiler/v5.6.5/node-v51-darwin-x64/profiler.node --module_name=profiler --module_path=/Users/arungupta/workspaces/localstack/localstack/dashboard/web/node_modules/v8-profiler/build/profiler/v5.6.5/node-v51-darwin-x64' (1)

> sauce-connect-launcher@0.13.0 postinstall /Users/arungupta/workspaces/localstack/localstack/dashboard/web/node_modules/sauce-connect-launcher
> node scripts/install.js
```

**Comment by whummer** [comment]
Thanks for reporting this bug. The `install-web` target has been fixed in version 0.3.4, can you please try again and check if the installation works for you now? (Installation does work now on travis-ci and in our Bitbucket pipelines build, but that environment might be different from your local machine. Alternatively, you could use the Docker image if you want to spin up the services.) Thanks
