### ISSUE TITLE
Any idea on " Timeout when waiting for KCL initialization. "

### ISSUE THREAD

**Issue by jiamo** [atlassian/localstack#45]
I install follow the step. And run the tests.test_integration get error:
```

# python -m tests.test_integration

Starting local Elasticsearch (port 4571)...
Starting mock S3 server (port 4572)...
Starting mock SNS server (port 4575)...
Starting mock SQS server (port 4576)...
Starting mock API Gateway (port 4567)...
Starting mock DynamoDB (port 4569)...
Starting mock DynamoDB Streams (port 4570)...
Starting mock Firehose (port 4573)...
Starting mock Lambda (port 4574)...
Starting mock Kinesis (port 4568)...
Starting mock Redshift server (port 4577)...
Ready.
Creating stream...
Shutdown
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/ubuntu/localstack/tests/test_integration.py", line 191, in <module>
    start_test(env=env)
  File "/home/ubuntu//localstack/tests/test_integration.py", line 137, in start_test
    wait_until_started=True)
  File "localstack/utils/kinesis/kinesis_connector.py", line 424, in listen_to_kinesis
    raise Exception('Timeout when waiting for KCL initialization.')
Exception: Timeout when waiting for KCL initialization.](url)

```

**Comment by whummer** [comment]
Can you please post the output of the following commands: 
```
ls .venv/lib/python2.7/site-packages/amazon_kclpy/jars/
```
```
(. .venv/bin/activate; python -c 'from localstack.utils.kinesis import kclipy_helper; print kclipy_helper.get_kcl_classpath()')
```
```
java -cp localstack/infra/amazon-kinesis-client/aws-java-sdk-sts.jar:.venv/lib/python2.7/site-packages/amazon_kclpy/jars/amazon-kinesis-client-1.7.2.jar:.venv/lib/python2.7/site-packages/amazon_kclpy/jars/aws-java-sdk-cloudwatch-1.11.14.jar:.venv/lib/python2.7/site-packages/amazon_kclpy/jars/aws-java-sdk-core-1.11.14.jar:.venv/lib/python2.7/site-packages/amazon_kclpy/jars/aws-java-sdk-dynamodb-1.11.14.jar:.venv/lib/python2.7/site-packages/amazon_kclpy/jars/aws-java-sdk-kinesis-1.11.14.jar:.venv/lib/python2.7/site-packages/amazon_kclpy/jars/aws-java-sdk-kms-1.11.14.jar:.venv/lib/python2.7/site-packages/amazon_kclpy/jars/aws-java-sdk-s3-1.11.14.jar:.venv/lib/python2.7/site-packages/amazon_kclpy/jars/commons-codec-1.9.jar:.venv/lib/python2.7/site-packages/amazon_kclpy/jars/commons-lang-2.6.jar:.venv/lib/python2.7/site-packages/amazon_kclpy/jars/commons-logging-1.1.3.jar:.venv/lib/python2.7/site-packages/amazon_kclpy/jars/guava-18.0.jar:.venv/lib/python2.7/site-packages/amazon_kclpy/jars/httpclient-4.5.2.jar:.venv/lib/python2.7/site-packages/amazon_kclpy/jars/httpcore-4.4.4.jar:.venv/lib/python2.7/site-packages/amazon_kclpy/jars/jackson-annotations-2.6.0.jar:.venv/lib/python2.7/site-packages/amazon_kclpy/jars/jackson-core-2.6.6.jar:.venv/lib/python2.7/site-packages/amazon_kclpy/jars/jackson-databind-2.6.6.jar:.venv/lib/python2.7/site-packages/amazon_kclpy/jars/jackson-dataformat-cbor-2.6.6.jar:.venv/lib/python2.7/site-packages/amazon_kclpy/jars/joda-time-2.8.1.jar:.venv/lib/python2.7/site-packages/amazon_kclpy/jars/protobuf-java-2.6.1.jar:/tmp:localstack/utils/kinesis/java com.atlassian.KinesisStarter ""
```

Also, which installation commands did you use exactly? I'm assuming you cloned the repo and then executed `make install`, is that right?

**Comment by jiamo** [comment]
I use `make install`.

```
$ ls .venv/lib/python2.7/site-packages/amazon_kclpy/jars/
amazon-kinesis-client-1.7.2.jar      aws-java-sdk-kinesis-1.11.14.jar  commons-lang-2.6.jar       httpcore-4.4.4.jar             jackson-core-2.6.6.jar             protobuf-java-2.6.1.jar
aws-java-sdk-cloudwatch-1.11.14.jar  aws-java-sdk-kms-1.11.14.jar      commons-logging-1.1.3.jar  __init__.py                    jackson-databind-2.6.6.jar
aws-java-sdk-core-1.11.14.jar        aws-java-sdk-s3-1.11.14.jar       guava-18.0.jar             __init__.pyc                   jackson-dataformat-cbor-2.6.6.jar
aws-java-sdk-dynamodb-1.11.14.jar    commons-codec-1.9.jar             httpclient-4.5.2.jar       jackson-annotations-2.6.0.jar  joda-time-2.8.1.jar

```
```
$ find localstack/utils/kinesis/java
localstack/utils/kinesis/java
localstack/utils/kinesis/java/com
localstack/utils/kinesis/java/com/atlassian
localstack/utils/kinesis/java/com/atlassian/DefaultSTSAssumeRoleSessionCredentialsProvider.java
localstack/utils/kinesis/java/com/atlassian/KinesisStarter.java
```

The last command give:

`Error:` Could not find or load main class com.atlassian.KinesisStarter

**Comment by whummer** [comment]
Ok, looks like the Java classes have not been compiled properly (you should see `KinesisStarter.class` and `DefaultSTSAssumeRoleSessionCredentialsProvider.class` in the same folder as the *.java files).

What is the output of the following commands:
```
which javac
```
```
javac -version
```
```
javac -version
```
```
which mvn
```
```
make compile
```

**Comment by jiamo** [comment]
```
 mvn --version
Apache Maven 3.0.5
Maven home: /usr/share/maven
Java version: 1.8.0_121, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-oracle/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.13.0-101-generic", arch: "amd64", family: "unix"
```

make compile:

```
import com.amazonaws.auth.STSAssumeRoleSessionCredentialsProvider;
                         ^
  symbol:   class STSAssumeRoleSessionCredentialsProvider
  location: package com.amazonaws.auth
localstack/utils/kinesis/java/com/atlassian/DefaultSTSAssumeRoleSessionCredentialsProvider.java:25: error: cannot find symbol
public class DefaultSTSAssumeRoleSessionCredentialsProvider extends STSAssumeRoleSessionCredentialsProvider {
                                                                    ^
  symbol: class STSAssumeRoleSessionCredentialsProvider
localstack/utils/kinesis/java/com/atlassian/DefaultSTSAssumeRoleSessionCredentialsProvider.java:54: error: cannot find symbol
                System.out.println(new DefaultSTSAssumeRoleSessionCredentialsProvider().getCredentials());
                                                                                       ^
  symbol:   method getCredentials()
  location: class DefaultSTSAssumeRoleSessionCredentialsProvider
3 errors
make: *** [compile] Error 1
```

**Comment by whummer** [comment]
Looks like a JAR file is missing on your machine, can you please run this:
```
ls -la localstack/infra/amazon-kinesis-client/aws-java-sdk-sts.jar
ls -la /tmp/aws-java-sdk-sts.jar
```
It should have been downloaded by `make install`. Do you have the `curl` command installed? It may have been some intermittent error, e.g., a network/download problem. Can you run the curl command directly:
```
curl -o localstack/infra/amazon-kinesis-client/aws-java-sdk-sts.jar http://central.maven.org/maven2/com/amazonaws/aws-java-sdk-sts/1.11.14/aws-java-sdk-sts-1.11.14.jar
```
If it succeeds, please try re-running the tests.

**Comment by jiamo** [comment]
`ls -la localstack/infra/amazon-kinesis-client/aws-java-sdk-sts.jar` no file.
`ls -la /tmp/aws-java-sdk-sts.jar` has file.

```
 curl -o localstack/infra/amazon-kinesis-client/aws-java-sdk-sts.jar http://central.maven.org/maven2/com/amazonaws/aws-java-sdk-sts/1.11.14/aws-java-sdk-sts-1.11.14.jar
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Warning: Failed to create the file
Warning: localstack/infra/amazon-kinesis-client/aws-java-sdk-sts.jar: No such
Warning: file or directory
  8  166k    8 13854    0     0   104k      0  0:00:01 --:--:--  0:00:01  104k
curl: (23) Failed writing body (0 != 13854)
```

**Seem like the `localstack/infra/amazon-kinesis-client` not exsit.**
I do `mkdir -p localstack/infra/amazon-kinesis-client` and recurl it.

At end . 
```
# make compile
# python -m tests.test_integration
No handlers could be found for logger "KCL"
No handlers could be found for logger "KCL"Kinesis consumer initialized.
Shutdown
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/ubuntu/localstack/tests/test_integration.py", line 191, in <module>
    start_test(env=env)
  File "/home/ubuntu/localstack/tests/test_integration.py", line 143, in start_test
    env=env, stream_view_type='NEW_AND_OLD_IMAGES')
  File "/home/ubuntu/localstack/tests/test_integration.py", line 66, in create_dynamodb_table
    StreamSpecification=stream_spec
  File "/home/ubuntu/localstack/.venv/local/lib/python2.7/site-packages/botocore/client.py", line 251, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/ubuntu/localstack/.venv/local/lib/python2.7/site-packages/botocore/client.py", line 537, in _make_api_call
    raise ClientError(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (ResourceInUseException) when calling the CreateTable operation:
```
The first problem is sloved ( I think there is a step cause the first problem and I meet it at antoher machin).

Any way the test ends with a  new error.  Should I close this and open a new issue?

**Comment by whummer** [comment]
I have a feeling that there might be still some leftover processes on your machine from the previous test run (which will interfere with the running the test again). Can you check the following output:
```
ps aux | grep 'moto_server\|kinesalite\|dynalite\|KinesisStarter\|bootstrap.Elasticsearch' | grep -v grep
```
If you can see any leftover processes in the output above, use this command to kill all those processes:
```
kill $(ps aux | grep 'moto_server\|kinesalite\|dynalite\|KinesisStarter\|bootstrap.Elasticsearch' | grep -v grep | awk '{print $2}')
```

**Comment by jiamo** [comment]
You are right. After kill the process. I got 

```
Ready.
Creating stream...
No handlers could be found for logger "KCL"
Kinesis consumer initialized.
Putting 10 items to table...
Waiting some time before finishing test.
DynamoDB updates retrieved via Kinesis (actual/expected): 10/10
Test finished successfully
Shutdown
```
Thanks for help. I can continue to have a look into it.
