### ISSUE TITLE
How to import external library

### ISSUE THREAD

**Issue by carlos-eduardo-gb** [atlassian/localstack#53]
How can i import a external library into Lambda? 

In AWS i just add the library in my package, but using the localstack i'm getting this error (eg. i'm trying to import avro)

`ERROR:lambda_mock:Exception on /2015-03-31/functions [POST]
Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/code/localstack/localstack/mock/apis/lambda_api.py", line 255, in create_function
    set_function_code(code, lambda_name)
  File "/opt/code/localstack/localstack/mock/apis/lambda_api.py", line 217, in set_function_code
    lambda_handler = exec_lambda_code(zip_file_content, lambda_cwd=lambda_cwd)
  File "/opt/code/localstack/localstack/mock/apis/lambda_api.py", line 157, in exec_lambda_code
    raise e
ImportError: No module named avro`

By build bash is
`zip -r lambda.zip avro elasticsearch aws_kinesis_agg urllib3 google`

Thanks,

**Comment by whummer** [comment]
Thanks for reporting. Fixed in this PR: https://bitbucket.org/atlassian/localstack/pull-requests/37

The version has not been bumped yet, I'm going to prepare a release with a new version tomorrow or later this week.
