### ISSUE TITLE
Master tests fail as of commit ca986970abd65a4b752c8ae835173c4b5f336002

### ISSUE THREAD

**Issue by lobster1234** [atlassian/localstack#60]
```
 ~/w/localstack   master  git pull origin master                                                                                                                                         Mon Apr 10 02:39:21 2017
From https://github.com/atlassian/localstack
 * branch            master     -> FETCH_HEAD
Already up-to-date.
 ~/w/localstack   master  git log -n 1                                                                                                                                           341ms  Mon Apr 10 02:39:26 2017
commit ca986970abd65a4b752c8ae835173c4b5f336002
Author: Waldemar Hummer <whummer@atlassian.com>
Date:   Sun Apr 9 14:13:37 2017 +0000

    Fix issue with Elasticsearch 5.x network bind
```

Make install produced quite a bit of warnings 

```
[WARNING] aws-java-sdk-dynamodb-1.11.0.jar, localstack-utils-1.0-SNAPSHOT.jar define 559 overlappping classes:
[WARNING] localstack-utils-1.0-SNAPSHOT.jar, aws-java-sdk-core-1.11.86.jar define 669 overlappping classes:
[WARNING] localstack-utils-1.0-SNAPSHOT.jar, joda-time-2.8.1.jar define 246 overlappping classes:
```

Make test fails on elasticsearch

```
~/w/localstack   master  make test                                                                                                                                              38.5s  Mon Apr 10 02:40:19 2017
make lint && \
		. .venv/bin/activate; DEBUG= PYTHONPATH=`pwd` nosetests --with-coverage --logging-level=WARNING --nocapture --no-skip --exe --cover-erase --cover-tests --cover-inclusive --cover-package=localstack --with-xunit --exclude='.venv.*' .
(. .venv/bin/activate; pep8 --max-line-length=120 --ignore=E128 --exclude=node_modules,legacy,.venv,dist .)
Starting local Elasticsearch (port 4571)...
Starting mock ES service (port 4578)...
Starting mock S3 server (port 4572)...
Starting mock SNS server (port 4575)...
Starting mock SQS server (port 4576)...
Starting mock API Gateway (port 4567)...
Starting mock DynamoDB (port 4569)...
Starting mock DynamoDB Streams (port 4570)...
Starting mock Firehose (port 4573)...
Starting mock Lambda (port 4574)...
Starting mock Kinesis (port 4568)...
Starting mock Redshift server (port 4577)...
Elasticsearch health check failed: ConnectionError(('Connection aborted.', BadStatusLine("''",))) caused by: ProtocolError(('Connection aborted.', BadStatusLine("''",))) Traceback (most recent call last):
  File "/Users/mpandit/work/localstack/localstack/mock/infra.py", line 247, in check_infra_elasticsearch
    out = es.cat.aliases()
  File "/Users/mpandit/work/localstack/.venv/lib/python2.7/site-packages/elasticsearch/client/utils.py", line 73, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/Users/mpandit/work/localstack/.venv/lib/python2.7/site-packages/elasticsearch/client/cat.py", line 23, in aliases
    'aliases', name), params=params)
  File "/Users/mpandit/work/localstack/.venv/lib/python2.7/site-packages/elasticsearch/transport.py", line 318, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/Users/mpandit/work/localstack/.venv/lib/python2.7/site-packages/elasticsearch/connection/http_urllib3.py", line 123, in perform_request
    raise ConnectionError('N/A', str(e), e)
ConnectionError: ConnectionError(('Connection aborted.', BadStatusLine("''",))) caused by: ProtocolError(('Connection aborted.', BadStatusLine("''",)))

ERROR checking state of local environment (after some retries): Traceback (most recent call last):
  File "/Users/mpandit/work/localstack/localstack/mock/infra.py", line 271, in check_infra
    check_infra_elasticsearch(expect_shutdown=expect_shutdown, print_error=print_error)
  File "/Users/mpandit/work/localstack/localstack/mock/infra.py", line 254, in check_infra_elasticsearch
    assert isinstance(out, basestring)
AssertionError

Shutdown
FStarting mock Kinesis (port 4568)...
Ready.
Shutdown
```

**Comment by lobster1234** [comment]
BTW I checked out 2a56b656b5b4ceeb03f484d56b2571fd647c92b3 from 4/4 and it passes the test so will use that in the meantime.

**Comment by whummer** [comment]
Hi, this issue might be related to a cached version of Elasticsearch on your local machine.

Can you please try to follow the steps described in this comment: https://github.com/atlassian/localstack/issues/56#issuecomment-292884965

Thanks

**Comment by lobster1234** [comment]
Thanks so much - the instructions worked and master passes tests. This issue can be closed per your process.

```
 !  ~/w/localstack   master  make test                                                                                                                                                  Mon Apr 10 11:59:45 2017
make lint && \
		. .venv/bin/activate; DEBUG= PYTHONPATH=`pwd` nosetests --with-coverage --logging-level=WARNING --nocapture --no-skip --exe --cover-erase --cover-tests --cover-inclusive --cover-package=localstack --with-xunit --exclude='.venv.*' .
(. .venv/bin/activate; pep8 --max-line-length=120 --ignore=E128 --exclude=node_modules,legacy,.venv,dist .)
Starting local Elasticsearch (port 4571)...
Starting mock ES service (port 4578)...
Starting mock S3 server (port 4572)...
Starting mock SNS server (port 4575)...
Starting mock SQS server (port 4576)...
Starting mock API Gateway (port 4567)...
Starting mock DynamoDB (port 4569)...
Starting mock DynamoDB Streams (port 4570)...
Starting mock Firehose (port 4573)...
Starting mock Lambda (port 4574)...
Starting mock Kinesis (port 4568)...
Starting mock Redshift server (port 4577)...
Ready.
Creating stream...
Kinesis consumer initialized.
Putting 10 items to table...
Waiting some time before finishing test.
DynamoDB updates retrieved via Kinesis (actual/expected): 10/10
Test finished successfully
Shutdown
.Starting mock Kinesis (port 4568)...
Ready.
Shutdown
```
