### ISSUE TITLE
Running Docker latest image getting a looping error

### ISSUE THREAD

**Issue by dmccullo** [atlassian/localstack#61]
Any help would be appreciated.
using docker command
docker run -it --name AWSLite -p 4567-4578:4567-4578 -p 8080:8080 atlassianlabs/localstack

Running on MacOS 10.12.4

Docker Version:
Version 17.03.1-ce-mac5 (16048)

getting this error over and over
AssertionError
make: [Makefile:49: infra] Error 1
2017-04-11 15:18:00,939 INFO exited: infra (exit status 2; expected)
2017-04-11 15:18:01,946 INFO spawned: 'infra' with pid 1016
. .venv/bin/activate; exec localstack/mock/infra.py
Starting local dev environment. CTRL-C to quit.
Starting local Elasticsearch (port 4571)...
Starting mock ES service (port 4578)...
Starting mock S3 server (port 4572)...
Starting mock SNS server (port 4575)...
Starting mock SQS server (port 4576)...
Starting mock API Gateway (port 4567)...
Starting mock DynamoDB (port 4569)...
Starting mock DynamoDB Streams (port 4570)...
Starting mock Firehose (port 4573)...
Starting mock Lambda (port 4574)...
Starting mock Kinesis (port 4568)...
Starting mock Redshift server (port 4577)...
2017-04-11 15:18:03,395 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Elasticsearch health check failed: ConnectionError(('Connection aborted.', BadStatusLine("''",))) caused by: ConnectionError(('Connection aborted.', BadStatusLine("''",))) Traceback (most recent call last):
File "localstack/mock/infra.py", line 247, in check_infra_elasticsearch
out = es.cat.aliases()
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/elasticsearch/client/utils.py", line 73, in _wrapped
return func(args, params=params, kwargs)
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/elasticsearch/client/cat.py", line 23, in aliases
'aliases', name), params=params)
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/elasticsearch/transport.py", line 318, in perform_request
status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/elasticsearch/connection/http_requests.py", line 84, in perform_request
raise ConnectionError('N/A', str(e), e)
ConnectionError: ConnectionError(('Connection aborted.', BadStatusLine("''",))) caused by: ConnectionError(('Connection aborted.', BadStatusLine("''",)))

**Comment by whummer** [comment]
Thanks for the report. I'm assuming this is version `0.3.9` of the Docker image? Can you please try running with the `DEBUG` environment variable enabled, then post the output here:
```
docker run -it --name AWSLite -e DEBUG=1 -p 4567-4578:4567-4578 -p 8080:8080 atlassianlabs/localstack
```

**Comment by dmccullo** [comment]
I am running latest which is currently 0.3.9 yes!
Just ran as requested

```
docker run -it --name AWSLite -e DEBUG=1 -p 4567-4578:4567-4578 -p 8080:8080 atlassianlabs/localstack
2017-04-12 12:48:15,441 INFO supervisord started with pid 1
2017-04-12 12:48:16,445 INFO spawned: 'dashboard' with pid 8
2017-04-12 12:48:16,449 INFO spawned: 'infra' with pid 9
(. .venv/bin/activate; bin/localstack web --port=8080)
. .venv/bin/activate; exec localstack/mock/infra.py
Starting local dev environment. CTRL-C to quit.
 * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
 * Restarting with stat
Starting local Elasticsearch (port 4571)...
Starting mock ES service (port 4578)...
Starting mock S3 server (port 4572)...
Starting mock SNS server (port 4575)...
Starting mock SQS server (port 4576)...
Starting mock API Gateway (port 4567)...
Starting mock DynamoDB (port 4569)...
Starting mock DynamoDB Streams (port 4570)...
Starting mock Firehose (port 4573)...
Starting mock Lambda (port 4574)...
Starting mock Kinesis (port 4568)...
Starting mock Redshift server (port 4577)...
 * Debugger is active!
2017-04-12 12:48:17,753 INFO success: dashboard entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2017-04-12 12:48:17,753 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
 * Debugger PIN: 410-955-455
Listening at http://:::4580
 * Running on http://0.0.0.0:4579/ (Press CTRL+C to quit)
 * Running on http://0.0.0.0:4572/ (Press CTRL+C to quit)
Listening at http://:::4581
 * Running on http://0.0.0.0:4577/ (Press CTRL+C to quit)
 * Running on http://0.0.0.0:4582/ (Press CTRL+C to quit)
 * Running on http://0.0.0.0:4576/ (Press CTRL+C to quit)
[2017-04-12T12:48:22,297][INFO ][o.e.n.Node               ] [] initializing ...
[2017-04-12T12:48:22,383][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: java.lang.IllegalStateException: failed to obtain node locks, tried [[/opt/code/localstack/localstack/infra/elasticsearch/data/elasticsearch]] with lock id [0]; maybe these locations are not writable or multiple nodes were started without increasing [node.max_local_storage_nodes] (was [1])?
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:127) ~[elasticsearch-5.3.0.jar:5.3.0]
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:114) ~[elasticsearch-5.3.0.jar:5.3.0]
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:58) ~[elasticsearch-5.3.0.jar:5.3.0]
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122) ~[elasticsearch-5.3.0.jar:5.3.0]
	at org.elasticsearch.cli.Command.main(Command.java:88) ~[elasticsearch-5.3.0.jar:5.3.0]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:91) ~[elasticsearch-5.3.0.jar:5.3.0]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:84) ~[elasticsearch-5.3.0.jar:5.3.0]
Caused by: java.lang.IllegalStateException: failed to obtain node locks, tried [[/opt/code/localstack/localstack/infra/elasticsearch/data/elasticsearch]] with lock id [0]; maybe these locations are not writable or multiple nodes were started without increasing [node.max_local_storage_nodes] (was [1])?
	at org.elasticsearch.env.NodeEnvironment.<init>(NodeEnvironment.java:260) ~[elasticsearch-5.3.0.jar:5.3.0]
	at org.elasticsearch.node.Node.<init>(Node.java:258) ~[elasticsearch-5.3.0.jar:5.3.0]
	at org.elasticsearch.node.Node.<init>(Node.java:238) ~[elasticsearch-5.3.0.jar:5.3.0]
	at org.elasticsearch.bootstrap.Bootstrap$6.<init>(Bootstrap.java:242) ~[elasticsearch-5.3.0.jar:5.3.0]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:242) ~[elasticsearch-5.3.0.jar:5.3.0]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:360) ~[elasticsearch-5.3.0.jar:5.3.0]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:123) ~[elasticsearch-5.3.0.jar:5.3.0]
	... 6 more
Caused by: java.io.IOException: failed to obtain lock on /opt/code/localstack/localstack/infra/elasticsearch/data/nodes/0
	at org.elasticsearch.env.NodeEnvironment.<init>(NodeEnvironment.java:239) ~[elasticsearch-5.3.0.jar:5.3.0]
	at org.elasticsearch.node.Node.<init>(Node.java:258) ~[elasticsearch-5.3.0.jar:5.3.0]
	at org.elasticsearch.node.Node.<init>(Node.java:238) ~[elasticsearch-5.3.0.jar:5.3.0]
	at org.elasticsearch.bootstrap.Bootstrap$6.<init>(Bootstrap.java:242) ~[elasticsearch-5.3.0.jar:5.3.0]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:242) ~[elasticsearch-5.3.0.jar:5.3.0]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:360) ~[elasticsearch-5.3.0.jar:5.3.0]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:123) ~[elasticsearch-5.3.0.jar:5.3.0]
	... 6 more
Caused by: java.io.IOException: Mount point not found
	at sun.nio.fs.LinuxFileStore.findMountEntry(LinuxFileStore.java:91) ~[?:?]
	at sun.nio.fs.UnixFileStore.<init>(UnixFileStore.java:65) ~[?:?]
	at sun.nio.fs.LinuxFileStore.<init>(LinuxFileStore.java:44) ~[?:?]
	at sun.nio.fs.LinuxFileSystemProvider.getFileStore(LinuxFileSystemProvider.java:51) ~[?:?]
	at sun.nio.fs.LinuxFileSystemProvider.getFileStore(LinuxFileSystemProvider.java:39) ~[?:?]
	at sun.nio.fs.UnixFileSystemProvider.getFileStore(UnixFileSystemProvider.java:368) ~[?:?]
	at java.nio.file.Files.getFileStore(Files.java:1461) ~[?:1.8.0_121]
	at org.elasticsearch.env.ESFileStore.getMatchingFileStore(ESFileStore.java:107) ~[elasticsearch-5.3.0.jar:5.3.0]
	at org.elasticsearch.env.Environment.getFileStore(Environment.java:340) ~[elasticsearch-5.3.0.jar:5.3.0]
	at org.elasticsearch.env.NodeEnvironment$NodePath.<init>(NodeEnvironment.java:108) ~[elasticsearch-5.3.0.jar:5.3.0]
	at org.elasticsearch.env.NodeEnvironment.<init>(NodeEnvironment.java:227) ~[elasticsearch-5.3.0.jar:5.3.0]
	at org.elasticsearch.node.Node.<init>(Node.java:258) ~[elasticsearch-5.3.0.jar:5.3.0]
	at org.elasticsearch.node.Node.<init>(Node.java:238) ~[elasticsearch-5.3.0.jar:5.3.0]
	at org.elasticsearch.bootstrap.Bootstrap$6.<init>(Bootstrap.java:242) ~[elasticsearch-5.3.0.jar:5.3.0]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:242) ~[elasticsearch-5.3.0.jar:5.3.0]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:360) ~[elasticsearch-5.3.0.jar:5.3.0]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:123) ~[elasticsearch-5.3.0.jar:5.3.0]
	... 6 more
172.17.0.3 - - [12/Apr/2017 12:48:22] "GET / HTTP/1.1" 200 -
172.17.0.3 - - [12/Apr/2017 12:48:25] "GET / HTTP/1.1" 200 -
172.17.0.3 - - [12/Apr/2017 12:48:28] "GET / HTTP/1.1" 200 -
172.17.0.3 - - [12/Apr/2017 12:48:31] "GET / HTTP/1.1" 200 -
172.17.0.3 - - [12/Apr/2017 12:48:34] "GET / HTTP/1.1" 200 -
172.17.0.3 - - [12/Apr/2017 12:48:37] "GET / HTTP/1.1" 200 -
172.17.0.3 - - [12/Apr/2017 12:48:40] "GET / HTTP/1.1" 200 -
172.17.0.3 - - [12/Apr/2017 12:48:44] "GET / HTTP/1.1" 200 -
Elasticsearch health check failed: ConnectionError(('Connection aborted.', BadStatusLine("''",))) caused by: ConnectionError(('Connection aborted.', BadStatusLine("''",))) Traceback (most recent call last):
  File "localstack/mock/infra.py", line 248, in check_infra_elasticsearch
    out = es.cat.aliases()
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/elasticsearch/client/utils.py", line 73, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/elasticsearch/client/cat.py", line 23, in aliases
    'aliases', name), params=params)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/elasticsearch/transport.py", line 318, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/elasticsearch/connection/http_requests.py", line 84, in perform_request
    raise ConnectionError('N/A', str(e), e)
ConnectionError: ConnectionError(('Connection aborted.', BadStatusLine("''",))) caused by: ConnectionError(('Connection aborted.', BadStatusLine("''",)))

ERROR checking state of local environment (after some retries): Traceback (most recent call last):
  File "localstack/mock/infra.py", line 272, in check_infra
    check_infra_elasticsearch(expect_shutdown=expect_shutdown, print_error=print_error)
  File "localstack/mock/infra.py", line 255, in check_infra_elasticsearch
    assert isinstance(out, basestring)
AssertionError

Traceback (most recent call last):
  File "localstack/mock/infra.py", line 377, in <module>
    start_infra()
  File "localstack/mock/infra.py", line 353, in start_infra
    check_infra(apis=apis)
  File "localstack/mock/infra.py", line 280, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "localstack/mock/infra.py", line 280, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "localstack/mock/infra.py", line 280, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "localstack/mock/infra.py", line 280, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "localstack/mock/infra.py", line 280, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "localstack/mock/infra.py", line 280, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "localstack/mock/infra.py", line 280, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "localstack/mock/infra.py", line 278, in check_infra
    raise e
AssertionError
```

Stuck here!

**Comment by whummer** [comment]
Thanks for posting the log. After a quick investigation, this might be related to this issue: https://github.com/elastic/elasticsearch-docker/issues/44 . A bug report has been raised against Alpine Linux (https://bugs.alpinelinux.org/issues/7093), but it is hard to anticipate when this will actually be fixed.

Possible solutions seem to include:
1) using a different base image (e.g., `maven:latest` instead of `maven:alpine`),
and/or
2) using a different storage engine (e.g., `DeviceMapper` instead of `overlay`) in your Docker environment
and/or
3) squashing the multiple layers of the Docker images into a single layer.

Option 3) is probably the easiest to try out first. Can you try running the following:
```
pip install docker-squash
docker-squash -t atlassianlabs/localstack:0.3.9-squashed atlassianlabs/localstack:0.3.9
docker run -it --name AWSLite -e DEBUG=1 -p 4567-4578:4567-4578 -p 8080:8080 atlassianlabs/localstack:0.3.9-squashed
```

(Note that the `docker-squash` command may take a while to complete.)

**Comment by whummer** [comment]
The workaround with squashed image seems to work, at least for one user (see https://github.com/atlassian/localstack/issues/58#issuecomment-293775319)

The image version `atlassianlabs/localstack:0.3.9` has been updated with the sqashed image. Please pull that version again and try starting the container:
```
docker pull atlassianlabs/localstack:0.3.9
docker run -it --name AWSLite -e DEBUG=1 -p 4567-4578:4567-4578 -p 8080:8080 atlassianlabs/localstack:0.3.9
```

Please confirm if that works for you @dmccullo

**Comment by Alan01252** [comment]
To confirm I was getting the same problem as above and pulling 0.3.9 has fixed it :) ty!

**Comment by apurva165** [comment]
i am getting the same error

**Comment by dmccullo** [comment]
That spun up perfectly...  now to figure out how to enable services and see how it all comes together lol
Very cool  thanks for the help and guidance!

**Comment by dmccullo** [comment]
You can consider this ticket resolved
