### ISSUE TITLE
docker error:docker is looping through it self because of an error

### ISSUE THREAD

**Issue by apurva165** [atlassian/localstack#64]
docker is looping through it self, 
tried docker run -it -p 4567-4578:4567-4578 -p 8080:8080 atlassianlabs/localstack
and make docker-run 
  
both giving me this result
make: *** [Makefile:49: infra] Error 1
2017-04-14 04:43:27,737 INFO exited: infra (exit status 2; expected)
2017-04-14 04:43:28,762 INFO spawned: 'infra' with pid 586
. .venv/bin/activate; exec localstack/mock/infra.py
Starting local dev environment. CTRL-C to quit.
Starting local Elasticsearch (port 4571)...
Starting mock ES service (port 4578)...
Starting mock S3 server (port 4572)...
Starting mock SNS server (port 4575)...
Starting mock SQS server (port 4576)...
Starting mock API Gateway (port 4567)...
Starting mock DynamoDB (port 4569)...
Starting mock DynamoDB Streams (port 4570)...
Starting mock Firehose (port 4573)...
Starting mock Lambda (port 4574)...
Starting mock Kinesis (port 4568)...
Starting mock Redshift server (port 4577)...
2017-04-14 04:43:30,541 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Elasticsearch health check failed: ConnectionError(('Connection aborted.', BadStatusLine("''",))) caused by: ConnectionError(('Connection aborted.', BadStatusLine("''",))) Traceback (most recent call last):
  File "localstack/mock/infra.py", line 248, in check_infra_elasticsearch
    out = es.cat.aliases()
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/elasticsearch/client/utils.py", line 73, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/elasticsearch/client/cat.py", line 23, in aliases
    'aliases', name), params=params)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/elasticsearch/transport.py", line 318, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/elasticsearch/connection/http_requests.py", line 84, in perform_request
    raise ConnectionError('N/A', str(e), e)
ConnectionError: ConnectionError(('Connection aborted.', BadStatusLine("''",))) caused by: ConnectionError(('Connection aborted.', BadStatusLine("''",)))

ERROR checking state of local environment (after some retries): Traceback (most recent call last):
  File "localstack/mock/infra.py", line 272, in check_infra
    check_infra_elasticsearch(expect_shutdown=expect_shutdown, print_error=print_error)
  File "localstack/mock/infra.py", line 255, in check_infra_elasticsearch
    assert isinstance(out, basestring)
AssertionError

Traceback (most recent call last):
  File "localstack/mock/infra.py", line 377, in <module>
    start_infra()
  File "localstack/mock/infra.py", line 353, in start_infra
    check_infra(apis=apis)
  File "localstack/mock/infra.py", line 280, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "localstack/mock/infra.py", line 280, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "localstack/mock/infra.py", line 280, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "localstack/mock/infra.py", line 280, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "localstack/mock/infra.py", line 280, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "localstack/mock/infra.py", line 280, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "localstack/mock/infra.py", line 280, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "localstack/mock/infra.py", line 278, in check_infra
    raise e
AssertionError
make: *** [Makefile:49: infra] Error 1
2017-04-14 04:43:57,034 INFO exited: infra (exit status 2; expected)
2017-04-14 04:43:58,052 INFO spawned: 'infra' with pid 756
. .venv/bin/activate; exec localstack/mock/infra.py
Starting local dev environment. CTRL-C to quit.
Starting local Elasticsearch (port 4571)...
Starting mock ES service (port 4578)...
Starting mock S3 server (port 4572)...
Starting mock SNS server (port 4575)...
Starting mock SQS server (port 4576)...
Starting mock API Gateway (port 4567)...
Starting mock DynamoDB (port 4569)...
Starting mock DynamoDB Streams (port 4570)...
Starting mock Firehose (port 4573)...
Starting mock Lambda (port 4574)...
Starting mock Kinesis (port 4568)...
Starting mock Redshift server (port 4577)...
2017-04-14 04:43:59,586 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Elasticsearch health check failed: ConnectionError(('Connection aborted.', BadStatusLine("''",))) caused by: ConnectionError(('Connection aborted.', BadStatusLine("''",))) Traceback (most recent call last):
  File "localstack/mock/infra.py", line 248, in check_infra_elasticsearch
    out = es.cat.aliases()
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/elasticsearch/client/utils.py", line 73, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/elasticsearch/client/cat.py", line 23, in aliases
    'aliases', name), params=params)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/elasticsearch/transport.py", line 318, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/elasticsearch/connection/http_requests.py", line 84, in perform_request
    raise ConnectionError('N/A', str(e), e)
ConnectionError: ConnectionError(('Connection aborted.', BadStatusLine("''",))) caused by: ConnectionError(('Connection aborted.', BadStatusLine("''",)))

ERROR checking state of local environment (after some retries): Traceback (most recent call last):
  File "localstack/mock/infra.py", line 272, in check_infra
    check_infra_elasticsearch(expect_shutdown=expect_shutdown, print_error=print_error)
  File "localstack/mock/infra.py", line 255, in check_infra_elasticsearch
    assert isinstance(out, basestring)
AssertionError

Traceback (most recent call last):
  File "localstack/mock/infra.py", line 377, in <module>
    start_infra()
  File "localstack/mock/infra.py", line 353, in start_infra
    check_infra(apis=apis)
  File "localstack/mock/infra.py", line 280, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "localstack/mock/infra.py", line 280, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "localstack/mock/infra.py", line 280, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "localstack/mock/infra.py", line 280, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "localstack/mock/infra.py", line 280, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "localstack/mock/infra.py", line 280, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "localstack/mock/infra.py", line 280, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "localstack/mock/infra.py", line 278, in check_infra
    raise e
AssertionError
make: *** [Makefile:49: infra] Error 1
2017-04-14 04:44:26,244 INFO exited: infra (exit status 2; expected)
2017-04-14 04:44:27,263 INFO spawned: 'infra' with pid 926
. .venv/bin/activate; exec localstack/mock/infra.py
Starting local dev environment. CTRL-C to quit.
Starting local Elasticsearch (port 4571)...
Starting mock ES service (port 4578)...
Starting mock S3 server (port 4572)...
Starting mock SNS server (port 4575)...
Starting mock SQS server (port 4576)...
Starting mock API Gateway (port 4567)...
Starting mock DynamoDB (port 4569)...
Starting mock DynamoDB Streams (port 4570)...
Starting mock Firehose (port 4573)...
Starting mock Lambda (port 4574)...
Starting mock Kinesis (port 4568)...
Starting mock Redshift server (port 4577)...
2017-04-14 04:44:28,786 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
^C2017-04-14 04:44:31,338 WARN received SIGINT indicating exit request
2017-04-14 04:44:31,339 INFO waiting for dashboard, infra to die
2017-04-14 04:44:32,346 INFO stopped: infra (terminated by SIGTERM)
make: *** [Makefile:63: web] Terminated
2017-04-14 04:44:32,348 INFO stopped: dashboard (terminated by SIGTERM)
slmbp1607:localstack apurvakulkarni$ make docker-run 
port_mappings=""; \
		docker run -it -e DEBUG= -e SERVICES= -e KINESIS_ERROR_PROBABILITY= -e SERVICES= -p 4567-4578:4567-4578 -p 8080:8080 $port_mappings atlassianlabs/localstack
2017-04-14 04:44:57,556 INFO supervisord started with pid 1
2017-04-14 04:44:58,559 INFO spawned: 'dashboard' with pid 9
2017-04-14 04:44:58,561 INFO spawned: 'infra' with pid 10
(. .venv/bin/activate; bin/localstack web --port=8080)
. .venv/bin/activate; exec localstack/mock/infra.py
Starting local dev environment. CTRL-C to quit.
 * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
 * Restarting with stat
Starting local Elasticsearch (port 4571)...
Starting mock ES service (port 4578)...
Starting mock S3 server (port 4572)...
Starting mock SNS server (port 4575)...
Starting mock SQS server (port 4576)...
Starting mock API Gateway (port 4567)...
Starting mock DynamoDB (port 4569)...
Starting mock DynamoDB Streams (port 4570)...
Starting mock Firehose (port 4573)...
Starting mock Lambda (port 4574)...
Starting mock Kinesis (port 4568)...
Starting mock Redshift server (port 4577)...
 * Debugger is active!
 * Debugger PIN: 135-536-443
2017-04-14 04:45:00,336 INFO success: dashboard entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2017-04-14 04:45:00,337 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Elasticsearch health check failed: ConnectionError(('Connection aborted.', BadStatusLine("''",))) caused by: ConnectionError(('Connection aborted.', BadStatusLine("''",))) Traceback (most recent call last):
  File "localstack/mock/infra.py", line 248, in check_infra_elasticsearch
    out = es.cat.aliases()
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/elasticsearch/client/utils.py", line 73, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/elasticsearch/client/cat.py", line 23, in aliases
    'aliases', name), params=params)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/elasticsearch/transport.py", line 318, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/elasticsearch/connection/http_requests.py", line 84, in perform_request
    raise ConnectionError('N/A', str(e), e)
ConnectionError: ConnectionError(('Connection aborted.', BadStatusLine("''",))) caused by: ConnectionError(('Connection aborted.', BadStatusLine("''",)))

ERROR checking state of local environment (after some retries): Traceback (most recent call last):
  File "localstack/mock/infra.py", line 272, in check_infra
    check_infra_elasticsearch(expect_shutdown=expect_shutdown, print_error=print_error)
  File "localstack/mock/infra.py", line 255, in check_infra_elasticsearch
    assert isinstance(out, basestring)
AssertionError

Traceback (most recent call last):
  File "localstack/mock/infra.py", line 377, in <module>
    start_infra()
  File "localstack/mock/infra.py", line 353, in start_infra
    check_infra(apis=apis)
  File "localstack/mock/infra.py", line 280, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "localstack/mock/infra.py", line 280, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "localstack/mock/infra.py", line 280, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "localstack/mock/infra.py", line 280, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "localstack/mock/infra.py", line 280, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "localstack/mock/infra.py", line 280, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "localstack/mock/infra.py", line 280, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "localstack/mock/infra.py", line 278, in check_infra
    raise e
AssertionError
make: *** [Makefile:49: infra] Error 1
2017-04-14 04:45:27,085 INFO exited: infra (exit status 2; expected)
2017-04-14 04:45:28,103 INFO spawned: 'infra' with pid 191
. .venv/bin/activate; exec localstack/mock/infra.py
Starting local dev environment. CTRL-C to quit.
Starting local Elasticsearch (port 4571)...
Starting mock ES service (port 4578)...
Starting mock S3 server (port 4572)...
Starting mock SNS server (port 4575)...
Starting mock SQS server (port 4576)...
Starting mock API Gateway (port 4567)...
Starting mock DynamoDB (port 4569)...
Starting mock DynamoDB Streams (port 4570)...
Starting mock Firehose (port 4573)...
Starting mock Lambda (port 4574)...
Starting mock Kinesis (port 4568)...
Starting mock Redshift server (port 4577)...
2017-04-14 04:45:29,864 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Elasticsearch health check failed: ConnectionError(('Connection aborted.', BadStatusLine("''",))) caused by: ConnectionError(('Connection aborted.', BadStatusLine("''",))) Traceback (most recent call last):
  File "localstack/mock/infra.py", line 248, in check_infra_elasticsearch
    out = es.cat.aliases()
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/elasticsearch/client/utils.py", line 73, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/elasticsearch/client/cat.py", line 23, in aliases
    'aliases', name), params=params)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/elasticsearch/transport.py", line 318, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/elasticsearch/connection/http_requests.py", line 84, in perform_request
    raise ConnectionError('N/A', str(e), e)
ConnectionError: ConnectionError(('Connection aborted.', BadStatusLine("''",))) caused by: ConnectionError(('Connection aborted.', BadStatusLine("''",)))

ERROR checking state of local environment (after some retries): Traceback (most recent call last):
  File "localstack/mock/infra.py", line 272, in check_infra
    check_infra_elasticsearch(expect_shutdown=expect_shutdown, print_error=print_error)
  File "localstack/mock/infra.py", line 255, in check_infra_elasticsearch
    assert isinstance(out, basestring)
AssertionError

Traceback (most recent call last):
  File "localstack/mock/infra.py", line 377, in <module>
    start_infra()
  File "localstack/mock/infra.py", line 353, in start_infra
    check_infra(apis=apis)
  File "localstack/mock/infra.py", line 280, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "localstack/mock/infra.py", line 280, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "localstack/mock/infra.py", line 280, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "localstack/mock/infra.py", line 280, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "localstack/mock/infra.py", line 280, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "localstack/mock/infra.py", line 280, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "localstack/mock/infra.py", line 280, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "localstack/mock/infra.py", line 278, in check_infra
    raise e
AssertionError
make: *** [Makefile:49: infra] Error 1
2017-04-14 04:45:56,171 INFO exited: infra (exit status 2; expected)
2017-04-14 04:45:57,191 INFO spawned: 'infra' with pid 417
. .venv/bin/activate; exec localstack/mock/infra.py
Starting local dev environment. CTRL-C to quit.
Starting local Elasticsearch (port 4571)...
Starting mock ES service (port 4578)...
Starting mock S3 server (port 4572)...
Starting mock SNS server (port 4575)...
Starting mock SQS server (port 4576)...
Starting mock API Gateway (port 4567)...
Starting mock DynamoDB (port 4569)...
Starting mock DynamoDB Streams (port 4570)...
Starting mock Firehose (port 4573)...
Starting mock Lambda (port 4574)...
Starting mock Kinesis (port 4568)...
Starting mock Redshift server (port 4577)...
2017-04-14 04:45:58,696 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
^C2017-04-14 04:45:59,811 WARN received SIGINT indicating exit request
2017-04-14 04:45:59,813 INFO waiting for dashboard, infra to die
^C2017-04-14 04:46:00,007 WARN received SIGINT indicating exit request
^C2017-04-14 04:46:00,199 WARN received SIGINT indicating exit request
^C2017-04-14 04:46:00,363 WARN received SIGINT indicating exit request
^C2017-04-14 04:46:00,543 WARN received SIGINT indicating exit request
^C2017-04-14 04:46:00,719 WARN received SIGINT indicating exit request
2017-04-14 04:46:00,821 INFO stopped: infra (terminated by SIGTERM)
make: *** [Makefile:63: web] Terminated
2017-04-14 04:46:00,823 INFO stopped: dashboard (terminated by SIGTERM)
slmbp1607:localstack apurvakulkarni$ make infra
. .venv/bin/activate; exec localstack/mock/infra.py
/bin/sh: .venv/bin/activate: No such file or directory
make: *** [infra] Error 1
slmbp1607:localstack apurvakulkarni$ docker run -it -p 4567-4578:4567-4578 -p 8080:8080 atlassianlabs/localstack
2017-04-14 04:47:08,404 INFO supervisord started with pid 1
2017-04-14 04:47:09,408 INFO spawned: 'dashboard' with pid 8
2017-04-14 04:47:09,410 INFO spawned: 'infra' with pid 9
(. .venv/bin/activate; bin/localstack web --port=8080)
. .venv/bin/activate; exec localstack/mock/infra.py
Starting local dev environment. CTRL-C to quit.
 * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
 * Restarting with stat
Starting local Elasticsearch (port 4571)...
Starting mock ES service (port 4578)...
Starting mock S3 server (port 4572)...
Starting mock SNS server (port 4575)...
Starting mock SQS server (port 4576)...
Starting mock API Gateway (port 4567)...
Starting mock DynamoDB (port 4569)...
Starting mock DynamoDB Streams (port 4570)...
Starting mock Firehose (port 4573)...
Starting mock Lambda (port 4574)...
Starting mock Kinesis (port 4568)...
Starting mock Redshift server (port 4577)...
 * Debugger is active!
 * Debugger PIN: 135-536-443
2017-04-14 04:47:11,126 INFO success: dashboard entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2017-04-14 04:47:11,127 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Elasticsearch health check failed: ConnectionError(('Connection aborted.', BadStatusLine("''",))) caused by: ConnectionError(('Connection aborted.', BadStatusLine("''",))) Traceback (most recent call last):
  File "localstack/mock/infra.py", line 248, in check_infra_elasticsearch
    out = es.cat.aliases()
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/elasticsearch/client/utils.py", line 73, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/elasticsearch/client/cat.py", line 23, in aliases
    'aliases', name), params=params)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/elasticsearch/transport.py", line 318, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/elasticsearch/connection/http_requests.py", line 84, in perform_request
    raise ConnectionError('N/A', str(e), e)
ConnectionError: ConnectionError(('Connection aborted.', BadStatusLine("''",))) caused by: ConnectionError(('Connection aborted.', BadStatusLine("''",)))

ERROR checking state of local environment (after some retries): Traceback (most recent call last):
  File "localstack/mock/infra.py", line 272, in check_infra
    check_infra_elasticsearch(expect_shutdown=expect_shutdown, print_error=print_error)
  File "localstack/mock/infra.py", line 255, in check_infra_elasticsearch
    assert isinstance(out, basestring)
AssertionError

Traceback (most recent call last):
  File "localstack/mock/infra.py", line 377, in <module>
    start_infra()
  File "localstack/mock/infra.py", line 353, in start_infra
    check_infra(apis=apis)
  File "localstack/mock/infra.py", line 280, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "localstack/mock/infra.py", line 280, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "localstack/mock/infra.py", line 280, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "localstack/mock/infra.py", line 280, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "localstack/mock/infra.py", line 280, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "localstack/mock/infra.py", line 280, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "localstack/mock/infra.py", line 280, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "localstack/mock/infra.py", line 278, in check_infra
    raise e
AssertionError
make: *** [Makefile:49: infra] Error 1
2017-04-14 04:47:37,906 INFO exited: infra (exit status 2; expected)
2017-04-14 04:47:38,924 INFO spawned: 'infra' with pid 211
. .venv/bin/activate; exec localstack/mock/infra.py
Starting local dev environment. CTRL-C to quit.
Starting local Elasticsearch (port 4571)...
Starting mock ES service (port 4578)...
Starting mock S3 server (port 4572)...
Starting mock SNS server (port 4575)...
Starting mock SQS server (port 4576)...
Starting mock API Gateway (port 4567)...
Starting mock DynamoDB (port 4569)...
Starting mock DynamoDB Streams (port 4570)...
Starting mock Firehose (port 4573)...
Starting mock Lambda (port 4574)...
Starting mock Kinesis (port 4568)...
Starting mock Redshift server (port 4577)...
2017-04-14 04:47:40,431 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
^C2017-04-14 04:47:59,485 WARN received SIGINT indicating exit request
2017-04-14 04:47:59,486 INFO waiting for dashboard, infra to die
^C2017-04-14 04:47:59,640 WARN received SIGINT indicating exit request
^C2017-04-14 04:47:59,817 WARN received SIGINT indicating exit request
2017-04-14 04:48:00,495 INFO stopped: infra (terminated by SIGTERM)
make: *** [Makefile:63: web] Terminated
2017-04-14 04:48:00,498 INFO stopped: dashboard (terminated by SIGTERM)

**Comment by apurva165** [comment]
this is already open

**Comment by whummer** [comment]
@apurva165 have you tried running this with the `DEBUG` environment variable enabled?

```
docker pull atlassianlabs/localstack:0.3.9
docker run -it -e DEBUG=1 -p 4567-4578:4567-4578 -p 8080:8080 atlassianlabs/localstack:0.3.9
```

And can you confirm that you are getting the exact same error as described in https://github.com/atlassian/localstack/issues/61 , namely Elasticsearch unable to start up with the following error message:

```
...
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:360) ~[elasticsearch-5.3.0.jar:5.3.0]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:123) ~[elasticsearch-5.3.0.jar:5.3.0]
	... 6 more
Caused by: java.io.IOException: Mount point not found
	at sun.nio.fs.LinuxFileStore.findMountEntry(LinuxFileStore.java:91) ~[?:?]
	at sun.nio.fs.UnixFileStore.<init>(UnixFileStore.java:65) ~[?:?]
	at sun.nio.fs.LinuxFileStore.<init>(LinuxFileStore.java:44) ~[?:?]
...
```
