### ISSUE TITLE
Unable to use MessageAttributeValues with SQS

### ISSUE THREAD

**Issue by awesometown** [atlassian/localstack#78]
I'm trying to use localstack's SQS endpoint with a Java application and am running into some issues when sending MessageAttributeValues. Given this test code:

```
    @Test
    public void testMessageAttributeValues() {
        AmazonSQSAsync sqs = AmazonSQSAsyncClientBuilder.standard().withEndpointConfiguration(new AwsClientBuilder
                .EndpointConfiguration("http://localhost:4576", "us-east-1")).build();

        sqs.createQueue(new CreateQueueRequest("test-queue"));

        MessageAttributeValue value= new MessageAttributeValue();
        value.setDataType("Number.java.lang.Long");
        value.setStringValue("1493147359900");

        Map<String, MessageAttributeValue> mavs = new HashMap<>();
        mavs.put("timestamp", value);

        SendMessageResult result = sqs.sendMessage(new SendMessageRequest()
                .withQueueUrl("http://localhost:4576/123456789012/test-queue")
                .withMessageAttributes(mavs)
                .withMessageBody("foo"));
        System.out.println(result);
    }
```
I get:
```
15:26:13.661 [main] INFO com.amazonaws.http.DefaultErrorResponseHandler - Unable to parse HTTP response (Invocation Id:25b666a4-1136-bae4-f39d-666e59b56b58) content to XML document 'The message attribute 'timestamp' has an invalid message attribute type, the set of supported type prefixes is Binary, Number, and String.' 
org.xml.sax.SAXParseException: Content is not allowed in prolog.
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203)
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:177)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:400)
...
```
Debugging the HTTP request, I see the actual response appears to be:
```
"The message attribute 'timestamp' has an invalid message attribute type, the set of supported type prefixes is Binary, Number, and String."
```
As you can see in my test, I'm actually sending `Number.java.lang.Long` (this simulates what the messaging library I'm using in my application sends). Based on [Amazon's docs](http://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-message-attributes.html#message-attributes-data-types-validation), this should be allowed as a "CustomType". I think this is maybe a case of localstack being overly strict during validation?

If I change my test to just send `Number`, I instead get a different error:
```
15:31:09.263 [main] DEBUG com.amazonaws.request - Received successful response: 200, AWS Request ID: 27daac76-34dd-47df-bd01-1f6e873584a0
15:31:09.263 [main] DEBUG com.amazonaws.requestId - x-amzn-RequestId: not available
15:31:09.263 [main] DEBUG com.amazonaws.requestId - AWS Request ID: 27daac76-34dd-47df-bd01-1f6e873584a0
15:31:09.263 [main] DEBUG com.amazonaws.services.sqs.MessageMD5ChecksumHandler - Message body: foo
15:31:09.264 [main] DEBUG com.amazonaws.services.sqs.MessageMD5ChecksumHandler - Expected  MD5 of message body: acbd18db4cc2f85cedef654fccc4a4d8
15:31:09.264 [main] DEBUG com.amazonaws.services.sqs.MessageMD5ChecksumHandler - Message attribtues: {timestamp={StringValue: 1493147359900,StringListValues: [],BinaryListValues: [],DataType: Number}}
15:31:09.264 [main] DEBUG com.amazonaws.services.sqs.MessageMD5ChecksumHandler - Expected  MD5 of message attributes: 235c5c510d26fb653d073faed50ae77c

com.amazonaws.AmazonClientException: MD5 returned by SQS does not match the calculation on the original request. (MD5 calculated by the message attributes: "235c5c510d26fb653d073faed50ae77c", MD5 checksum returned: "324758f82d026ac6ec5b31a3b192d1e3")

	at com.amazonaws.services.sqs.MessageMD5ChecksumHandler.sendMessageOperationMd5Check(MessageMD5ChecksumHandler.java:120)
	at com.amazonaws.services.sqs.MessageMD5ChecksumHandler.afterResponse(MessageMD5ChecksumHandler.java:80)
	at com.amazonaws.handlers.RequestHandler2Adaptor.afterResponse(RequestHandler2Adaptor.java:49)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.afterResponse(AmazonHttpClient.java:971)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:745)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:716)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513)
	at com.amazonaws.services.sqs.AmazonSQSClient.doInvoke(AmazonSQSClient.java:1792)
	at com.amazonaws.services.sqs.AmazonSQSClient.invoke(AmazonSQSClient.java:1768)
	at com.amazonaws.services.sqs.AmazonSQSClient.executeSendMessage(AmazonSQSClient.java:1526)
	at com.amazonaws.services.sqs.AmazonSQSClient.sendMessage(AmazonSQSClient.java:1503)
```

If I don't send any MessageAttributes at all, then the request works as expected.

**Comment by whummer** [comment]
Thanks for the detailed bug report. We use `moto` as the underlying SQS mock implementation, and currently the MD5 hash for message attributes is not properly computed, i.e., the hash is simply hardcoded: https://github.com/spulec/moto/blob/896f040fca975865c1d441d90016446c72db3ed4/moto/sqs/responses.py#L343

Looks like there is no configuration option to disable these MD5 checks in the AWS Java SDK, so we should get this fixed in the mock. Would you be able to raise a PR against moto? Cheers

**Comment by whummer** [comment]
@awesometown The fix has now been merged into `moto`, we have bumped the version in LocalStack. Please pull the latest version and give it a try. Feel free to re-open if the problem persists. Thanks

**Comment by miron4dev** [comment]
I have the same issue with the latest LocalStack. Was something broken?
