### ISSUE TITLE
pip install localstack fails

### ISSUE THREAD

**Issue by bstent** [atlassian/localstack#81]
I get the following error tryingg to install localstack.  Can anybody help me with this?

    Compiling
    javac -cp /usr/lib/python2.7/site-packages/localstack/infra/amazon-kinesis-client/aws-java-sdk-sts.jar:/tmp/pip-build-d1H1Qn/localstack/.venv/lib/python2.7/site-packages/amazon_kclpy/jars/amazon-kinesis-client-1.7.2.jar:/tmp/pip-build-d1H1Qn/localstack/.venv/lib/python2.7/site-packages/amazon_kclpy/jars/aws-java-sdk-dynamodb-1.11.14.jar:/tmp/pip-build-d1H1Qn/localstack/.venv/lib/python2.7/site-packages/amazon_kclpy/jars/aws-java-sdk-s3-1.11.14.jar:/tmp/pip-build-d1H1Qn/localstack/.venv/lib/python2.7/site-packages/amazon_kclpy/jars/aws-java-sdk-kms-1.11.14.jar:/tmp/pip-build-d1H1Qn/localstack/.venv/lib/python2.7/site-packages/amazon_kclpy/jars/aws-java-sdk-core-1.11.14.jar:/tmp/pip-build-d1H1Qn/localstack/.venv/lib/python2.7/site-packages/amazon_kclpy/jars/commons-logging-1.1.3.jar:/tmp/pip-build-d1H1Qn/localstack/.venv/lib/python2.7/site-packages/amazon_kclpy/jars/httpclient-4.5.2.jar:/tmp/pip-build-d1H1Qn/localstack/.venv/lib/python2.7/site-packages/amazon_kclpy/jars/httpcore-4.4.4.jar:/tmp/pip-build-d1H1Qn/localstack/.venv/lib/python2.7/site-packages/amazon_kclpy/jars/commons-codec-1.9.jar:/tmp/pip-build-d1H1Qn/localstack/.venv/lib/python2.7/site-packages/amazon_kclpy/jars/jackson-databind-2.6.6.jar:/tmp/pip-build-d1H1Qn/localstack/.venv/lib/python2.7/site-packages/amazon_kclpy/jars/jackson-annotations-2.6.0.jar:/tmp/pip-build-d1H1Qn/localstack/.venv/lib/python2.7/site-packages/amazon_kclpy/jars/jackson-core-2.6.6.jar:/tmp/pip-build-d1H1Qn/localstack/.venv/lib/python2.7/site-packages/amazon_kclpy/jars/jackson-dataformat-cbor-2.6.6.jar:/tmp/pip-build-d1H1Qn/localstack/.venv/lib/python2.7/site-packages/amazon_kclpy/jars/joda-time-2.8.1.jar:/tmp/pip-build-d1H1Qn/localstack/.venv/lib/python2.7/site-packages/amazon_kclpy/jars/aws-java-sdk-kinesis-1.11.14.jar:/tmp/pip-build-d1H1Qn/localstack/.venv/lib/python2.7/site-packages/amazon_kclpy/jars/aws-java-sdk-cloudwatch-1.11.14.jar:/tmp/pip-build-d1H1Qn/localstack/.venv/lib/python2.7/site-packages/amazon_kclpy/jars/guava-18.0.jar:/tmp/pip-build-d1H1Qn/localstack/.venv/lib/python2.7/site-packages/amazon_kclpy/jars/protobuf-java-2.6.1.jar:/tmp/pip-build-d1H1Qn/localstack/.venv/lib/python2.7/site-packages/amazon_kclpy/jars/commons-lang-2.6.jar:/usr/lib/python2.7/site-packages/localstack/utils/kinesis/java localstack/utils/kinesis/java/com/atlassian/*.java
    make[1]: Leaving directory `/tmp/pip-build-d1H1Qn/localstack'

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-d1H1Qn/localstack/setup.py", line 108, in <module>
        "Topic :: Software Development :: Testing",
      File "/usr/lib64/python2.7/distutils/core.py", line 152, in setup
        dist.run_commands()
      File "/usr/lib64/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/usr/lib/python2.7/site-packages/setuptools/command/install.py", line 53, in run
        return _install.run(self)
      File "/usr/lib64/python2.7/distutils/command/install.py", line 575, in run
        self.run_command(cmd_name)
      File "/usr/lib64/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/tmp/pip-build-d1H1Qn/localstack/setup.py", line 61, in run
        do_make_install()
      File "/tmp/pip-build-d1H1Qn/localstack/setup.py", line 41, in do_make_install
        raise e
    subprocess.CalledProcessError: Command 'make install' returned non-zero exit status 2

    ----------------------------------------
Command "/usr/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-d1H1Qn/localstack/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-PBObek-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-d1H1Qn/localstack/
[root@bs-localstack ~]#

[root@bs-localstack ~]# java -version
openjdk version "1.8.0_102"
OpenJDK Runtime Environment (build 1.8.0_102-b14)
OpenJDK 64-Bit Server VM (build 25.102-b14, mixed mode)
[root@bs-localstack ~]# mvn --version
Apache Maven 3.5.0 (ff8f5e7444045639af65f6095c62210b5713f426; 2017-04-03T15:39:06-04:00)
Maven home: /opt/maven
Java version: 1.8.0_102, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.102-4.b14.el7.x86_64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.10.0-514.el7.x86_64", arch: "amd64", family: "unix"
[root@bs-localstack ~]# python --version
Python 2.7.5
[root@bs-localstack ~]# pip --version
pip 9.0.1 from /usr/lib/python2.7/site-packages (python 2.7)
[root@bs-localstack ~]# node --version
v6.10.2
[root@bs-localstack ~]# npm  --version
4.5.0
[root@bs-localstack ~]#

**Comment by bstent** [comment]
Sorry - didn't go back far enough --- was missing path to javac.... all good.
