### ISSUE TITLE
Unable to publish message through SNS->SQS

### ISSUE THREAD

**Issue by filiphaftek** [atlassian/localstack#83]
I've started localstack with default configuration (tested docker and `make infra` command). Then I've created:
1. queue: `aws --endpoint-url=http://localhost:4576 sqs create-queue --queue-name queue1`
2. topic: `aws --endpoint-url=http://localhost:4575 sns create-topic --name topic1`
3. subscription: `aws --endpoint-url=http://localhost:4575 sns subscribe --topic-arn arn:aws:sns:eu-west-1:XXXXX:topic1 --protocol sqs --notification-endpoint arn:aws:sqs:eu-west-1:XXXXX:queue1`
I've checked that subscription is created. I did not add SNS any additional permission nor confirmed subscription (as this is local I assume flow is more simplified. Am I correct?) 

When I've tried to publish message with command: `aws --endpoint-url=http://localhost:4575 sns publish --message text --topic-arn arn:aws:sns:eu-west-1:XXXXX:topic1` I see an error:
```
ERROR:localstack.mock.generic_proxy:Error forwarding request: Traceback (most recent call last):
  File "/opt/code/localstack/localstack/mock/generic_proxy.py", line 88, in forward
    data=data, headers=self.headers, return_forward_info=True)
  File "/opt/code/localstack/localstack/mock/proxy/sns_listener.py", line 37, in update_sns
    queue_url = aws_stack.get_sqs_queue_url(queue_name)
  File "/opt/code/localstack/localstack/utils/aws/aws_stack.py", line 285, in get_sqs_queue_url
    response = client.get_queue_url(QueueName=queue_name)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/botocore/client.py", line 253, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/botocore/client.py", line 531, in _make_api_call
    operation_model, request_dict)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/botocore/endpoint.py", line 141, in make_request
    return self._send_request(request_dict, operation_model)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/botocore/endpoint.py", line 168, in _send_request
    request, operation_model, attempts)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/botocore/endpoint.py", line 233, in _get_response
    response_dict, operation_model.output_shape)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/botocore/parsers.py", line 210, in parse
    parsed = self._do_error_parse(response, shape)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/botocore/parsers.py", line 438, in _do_error_parse
    root = self._parse_xml_string_to_dom(xml_contents)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/botocore/parsers.py", line 390, in _parse_xml_string_to_dom
    "invalid XML received:\n%s" % (e, xml_string))
ResponseParserError: Unable to parse response (syntax error: line 1, column 54), invalid XML received:
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>
```

Any help would be very appreciated.

**Comment by whummer** [comment]
Thanks for the report. Unfortunately, I was unable to reproduce your exact problem. What I did notice, though, is that the issue might be related to AWS region identifiers - you are using `eu-west-1` whereas `LocalStack` uses `us-east-1` by default. In fact, when I ran the 3rd command (sns subscribe), I received a 404 error that the topic does not exist.

Here is the detailed output:
```
$ aws --endpoint-url=http://localhost:4576 sqs create-queue --queue-name queue1
{
    "QueueUrl": "http://localhost:4576/123456789012/queue1"
}
$ aws --endpoint-url=http://localhost:4575 sns create-topic --name topic1
{
    "TopicArn": "arn:aws:sns:us-east-1:123456789012:topic1"
}
$ aws --endpoint-url=http://localhost:4575 sns subscribe --topic-arn arn:aws:sns:eu-west-1:XXXXX:topic1 --protocol sqs --notification-endpoint arn:aws:sqs:eu-west-1:XXXXX:queue1

An error occurred (NotFound) when calling the Subscribe operation: Topic with arn arn:aws:sns:eu-west-1:XXXXX:topic1 not found
```

It does work though, when I use region us-east-1 and the correct account id:
```
$ aws --endpoint-url=http://localhost:4575 sns subscribe --topic-arn arn:aws:sns:us-east-1:123456789012:topic1 --protocol sqs --notification-endpoint arn:aws:sqs:us-east-1:123456789012:queue1
{
    "SubscriptionArn": "arn:aws:sns:us-east-1:123456789012:topic1:b76bd4cd-02e5-4cd2-9d42-65019fbb6ee1"
}
$ aws --endpoint-url=http://localhost:4575 sns publish --message text --topic-arn arn:aws:sns:us-east-1:123456789012:topic1
{
    "MessageId": "n/a"
}
$ aws --endpoint-url=http://localhost:4576 sqs receive-message --queue-url http://localhost:4576/123456789012/queue1
{
    "Messages": [
        {
            "Body": "text", 
            "Attributes": {
                "ApproximateFirstReceiveTimestamp": "1.49372135947e+12", 
                "SenderId": "AIDAIT2UOQQY3AUEKVGXU", 
                "ApproximateReceiveCount": "1", 
                "SentTimestamp": "1.49372134801e+12"
            }, 
            "ReceiptHandle": "tkizhnpdehpnozdrcvinhczkzssjgyfjjztozonciiwgpgwseqxehwuzltsrgahcpfpjytsptfosomsnjpobeuzgtqtenuagamlxqyfrljzcvhatzypzkuhbezxelflapbujrmjbazyzecngnrqiuxvpjogizadvmepsrrndtzcjqmeaoqwtmmpcx", 
            "MD5OfBody": "1cb251ec0d568de6a929b520c4aed8d1", 
            "MessageId": "5b4aff10-6f4e-12ea-0985-689361089e1e"
        }
    ]
}
```

Can you confirm that the above commands also work for you? The region-related issue is a bug, and we will have to investigate how we can fix that across the code base. But for now, as a quick fix, it should work if you use `us-east-1` in your tests.

**Comment by filiphaftek** [comment]
Yes, I confirm that when `us-east-1` is used as a default region, the flow is working fine. Thank you.
