### ISSUE TITLE
Worker fails to Initialize (404 on SyncShards)

### ISSUE THREAD

**Issue by msumner91** [atlassian/localstack#87]
The AWS com.amazonaws.services.kinesis.clientlibrary.lib.worker.Worker fails to sync shards during initialize() (see stack traces below).

**Error response:**
`10:57:36.486 [Thread-4] DEBUG c.a.s.k.leases.impl.LeaseManager - Lease table exists and is in status ACTIVE
10:57:36.521 [Thread-4] DEBUG com.amazonaws.request - Received error response: com.amazonaws.services.kinesis.model.AmazonKinesisException: null (Service: AmazonKinesis; Status Code: 404; Error Code: null; Request ID: 560c5d60-2f8b-11e7-b587-3f8e4fa4ca65)
    10:57:36.521 [Thread-4] ERROR c.a.s.k.c.lib.worker.ShardSyncTask - Caught exception while sync'ing Kinesis shards and leases`

The client successfully connects to kinesis, dynamodb and the lease co-ordinator initializes as expected (creating missing tables etc). However, the call to ShardSyncTask fails in the end resulting in a 404.

**Additional:** 
- We are using the latest [LocalStack](https://github.com/atlassian/localstack) docker image to spin up a local instance of Kinesis and DynamoDb and connecting to it with the KinesisClient.
- Client version 1.7.5

**Request debug output:**
10:57:36.486 [Thread-4] DEBUG c.a.s.k.leases.impl.LeaseManager - Lease table exists and is in status ACTIVE
    10:57:36.486 [Thread-4] INFO  c.a.s.k.c.lib.worker.Worker - Syncing Kinesis shard info
    10:57:36.501 [Thread-4] DEBUG com.amazonaws.request - Sending Request: POST http://localhost:4568 / Headers: (User-Agent: ads-publisher-changelog-test,amazon-kinesis-client-library-java-1.7.4, aws-sdk-java/1.11.115 Mac_OS_X/10.12.3 Java_HotSpot(TM)_64-Bit_Server_VM/25.121-b13/1.8.0_121 scala/2.11.8, amz-sdk-invocation-id: c66830f0-f5c0-abcf-1840-fad18ea66083, Content-Length: 43, X-Amz-Target: Kinesis_20131202.DescribeStream, Content-Type: application/x-amz-cbor-1.1, ) 
    10:57:36.501 [Thread-4] DEBUG com.amazonaws.auth.AWS4Signer - AWS4 Canonical Request: '"POST / amz-sdk-invocation-id:c66830f0-f5c0-abcf-1840-fad18ea66083
    amz-sdk-retry:0/0/500
    content-length:43
    content-type:application/x-amz-cbor-1.1
    host:localhost:4568
    user-agent:ads-publisher-changelog-test,amazon-kinesis-client-library-java-1.7.4, aws-sdk-java/1.11.115 Mac_OS_X/10.12.3 Java_HotSpot(TM)_64-Bit_Server_VM/25.121-b13/1.8.0_121 scala/2.11.8
    x-amz-date:20170503T095736Z
    x-amz-target:Kinesis_20131202.DescribeStream
amz-sdk-invocation-id;amz-sdk-retry;content-length;content-type;host;user-agent;x-amz-date;x-amz-target
    19c76a194d6804f1d7d30898c017199da0f97a8c9e86e815a78b4975e24af5f6"
    10:57:36.501 [Thread-4] DEBUG com.amazonaws.auth.AWS4Signer - AWS4 String to Sign: '"AWS4-HMAC-SHA256
    20170503T095736Z
    20170503/us-east-1/kinesis/aws4_request
    2987b39151bc7d8458fc05ff7303ba3e134ee7467c6d2a29eb411802d1cb1123"
    10:57:36.501 [Thread-4] DEBUG com.amazonaws.auth.AWS4Signer - Generating a new signing key as the signing key not available in the cache for the date 1493769600000
    10:57:36.502 [Thread-4] DEBUG o.a.h.c.protocol.RequestAddCookies - CookieSpec selected: default
    10:57:36.502 [Thread-4] DEBUG o.a.h.c.protocol.RequestAuthCache - Auth cache not set in the context
    10:57:36.502 [Thread-4] DEBUG o.a.h.i.c.PoolingHttpClientConnectionManager - Connection request: [route: {}->http://localhost:4568][total kept alive: 0; route allocated: 0 of 50; total allocated: 0 of 50]
    10:57:36.502 [Thread-4] DEBUG o.a.h.i.c.PoolingHttpClientConnectionManager - Connection leased: [id: 1][route: {}->http://localhost:4568][total kept alive: 0; route allocated: 1 of 50; total allocated: 1 of 50]
    10:57:36.503 [Thread-4] DEBUG o.a.h.impl.execchain.MainClientExec - Opening connection {}->http://localhost:4568
    10:57:36.503 [Thread-4] DEBUG o.a.h.i.c.DefaultHttpClientConnectionOperator - Connecting to localhost/127.0.0.1:4568
    10:57:36.503 [Thread-4] DEBUG o.a.h.i.c.DefaultHttpClientConnectionOperator - Connection established 127.0.0.1:62607<->127.0.0.1:4568
    10:57:36.503 [Thread-4] DEBUG o.a.h.i.c.DefaultManagedHttpClientConnection - http-outgoing-1: set socket timeout to 50000
    10:57:36.503 [Thread-4] DEBUG o.a.h.impl.execchain.MainClientExec - Executing request POST / HTTP/1.1
    10:57:36.503 [Thread-4] DEBUG o.a.h.impl.execchain.MainClientExec - Proxy auth state: UNCHALLENGED
    10:57:36.503 [Thread-4] DEBUG org.apache.http.headers - http-outgoing-1 >> POST / HTTP/1.1
    10:57:36.503 [Thread-4] DEBUG org.apache.http.headers - http-outgoing-1 >> Host: localhost:4568
    10:57:36.503 [Thread-4] DEBUG org.apache.http.headers - http-outgoing-1 >> Authorization: AWS4-HMAC-SHA256 Credential=foo/20170503/us-east-1/kinesis/aws4_request, SignedHeaders=amz-sdk-invocation-id;amz-sdk-retry;content-length;content-type;host;user-agent;x-amz-date;x-amz-target, Signature=00b8f7614947a9acde4ccd277bf181efea1c8c595a67711cc724ea19179c347b
    10:57:36.503 [Thread-4] DEBUG org.apache.http.headers - http-outgoing-1 >> X-Amz-Date: 20170503T095736Z
    10:57:36.504 [Thread-4] DEBUG org.apache.http.headers - http-outgoing-1 >> User-Agent: ads-publisher-changelog-test,amazon-kinesis-client-library-java-1.7.4, aws-sdk-java/1.11.115 Mac_OS_X/10.12.3 Java_HotSpot(TM)_64-Bit_Server_VM/25.121-b13/1.8.0_121 scala/2.11.8
    10:57:36.504 [Thread-4] DEBUG org.apache.http.headers - http-outgoing-1 >> amz-sdk-invocation-id: c66830f0-f5c0-abcf-1840-fad18ea66083
    10:57:36.504 [Thread-4] DEBUG org.apache.http.headers - http-outgoing-1 >> amz-sdk-retry: 0/0/500
    10:57:36.504 [Thread-4] DEBUG org.apache.http.headers - http-outgoing-1 >> X-Amz-Target: Kinesis_20131202.DescribeStream
    10:57:36.504 [Thread-4] DEBUG org.apache.http.headers - http-outgoing-1 >> Content-Type: application/x-amz-cbor-1.1
    10:57:36.504 [Thread-4] DEBUG org.apache.http.headers - http-outgoing-1 >> Content-Length: 43
    10:57:36.504 [Thread-4] DEBUG org.apache.http.headers - http-outgoing-1 >> Connection: Keep-Alive
    10:57:36.504 [Thread-4] DEBUG org.apache.http.wire - http-outgoing-1 >> "POST / HTTP/1.1[\r][\n]"
    10:57:36.504 [Thread-4] DEBUG org.apache.http.wire - http-outgoing-1 >> "Host: localhost:4568[\r][\n]"
    10:57:36.504 [Thread-4] DEBUG org.apache.http.wire - http-outgoing-1 >> "Authorization: AWS4-HMAC-SHA256 Credential=foo/20170503/us-east-1/kinesis/aws4_request, SignedHeaders=amz-sdk-invocation-id;amz-sdk-retry;content-length;content-type;host;user-agent;x-amz-date;x-amz-target, Signature=00b8f7614947a9acde4ccd277bf181efea1c8c595a67711cc724ea19179c347b[\r][\n]"
    10:57:36.504 [Thread-4] DEBUG org.apache.http.wire - http-outgoing-1 >> "X-Amz-Date: 20170503T095736Z[\r][\n]"
    10:57:36.504 [Thread-4] DEBUG org.apache.http.wire - http-outgoing-1 >> "User-Agent: ads-publisher-changelog-test,amazon-kinesis-client-library-java-1.7.4, aws-sdk-java/1.11.115 Mac_OS_X/10.12.3 Java_HotSpot(TM)_64-Bit_Server_VM/25.121-b13/1.8.0_121 scala/2.11.8[\r][\n]"
    10:57:36.504 [Thread-4] DEBUG org.apache.http.wire - http-outgoing-1 >> "amz-sdk-invocation-id: c66830f0-f5c0-abcf-1840-fad18ea66083[\r][\n]"
    10:57:36.504 [Thread-4] DEBUG org.apache.http.wire - http-outgoing-1 >> "amz-sdk-retry: 0/0/500[\r][\n]"
    10:57:36.504 [Thread-4] DEBUG org.apache.http.wire - http-outgoing-1 >> "X-Amz-Target: Kinesis_20131202.DescribeStream[\r][\n]"
    10:57:36.504 [Thread-4] DEBUG org.apache.http.headers - http-outgoing-1 >> Content-Type: application/x-amz-cbor-1.1
        10:57:36.504 [Thread-4] DEBUG org.apache.http.headers - http-outgoing-1 >> Content-Length: 43
        10:57:36.504 [Thread-4] DEBUG org.apache.http.headers - http-outgoing-1 >> Connection: Keep-Alive
        10:57:36.504 [Thread-4] DEBUG org.apache.http.wire - http-outgoing-1 >> "POST / HTTP/1.1[\r][\n]"
        10:57:36.504 [Thread-4] DEBUG org.apache.http.wire - http-outgoing-1 >> "Host: localhost:4568[\r][\n]"
        10:57:36.504 [Thread-4] DEBUG org.apache.http.wire - http-outgoing-1 >> "Authorization: AWS4-HMAC-SHA256 Credential=foo/20170503/us-east-1/kinesis/aws4_request, SignedHeaders=amz-sdk-invocation-id;amz-sdk-retry;content-length;content-type;host;user-agent;x-amz-date;x-amz-target, Signature=00b8f7614947a9acde4ccd277bf181efea1c8c595a67711cc724ea19179c347b[\r][\n]"
        10:57:36.504 [Thread-4] DEBUG org.apache.http.wire - http-outgoing-1 >> "X-Amz-Date: 20170503T095736Z[\r][\n]"
        10:57:36.504 [Thread-4] DEBUG org.apache.http.wire - http-outgoing-1 >> "User-Agent: ads-publisher-changelog-test,amazon-kinesis-client-library-java-1.7.4, aws-sdk-java/1.11.115 Mac_OS_X/10.12.3 Java_HotSpot(TM)_64-Bit_Server_VM/25.121-b13/1.8.0_121 scala/2.11.8[\r][\n]"
        10:57:36.504 [Thread-4] DEBUG org.apache.http.wire - http-outgoing-1 >> "amz-sdk-invocation-id: c66830f0-f5c0-abcf-1840-fad18ea66083[\r][\n]"
        10:57:36.504 [Thread-4] DEBUG org.apache.http.wire - http-outgoing-1 >> "amz-sdk-retry: 0/0/500[\r][\n]"
        10:57:36.504 [Thread-4] DEBUG org.apache.http.wire - http-outgoing-1 >> "X-Amz-Target: Kinesis_20131202.DescribeStream[\r][\n]"
        10:57:36.504 [Thread-4] DEBUG org.apache.http.wire - http-outgoing-1 >> "Content-Type: application/x-amz-cbor-1.1[\r][\n]"
        10:57:36.504 [Thread-4] DEBUG org.apache.http.wire - http-outgoing-1 >> "Content-Length: 43[\r][\n]"
        10:57:36.504 [Thread-4] DEBUG org.apache.http.wire - http-outgoing-1 >> "Connection: Keep-Alive[\r][\n]"
        10:57:36.504 [Thread-4] DEBUG org.apache.http.wire - http-outgoing-1 >> "[\r][\n]"
        10:57:36.504 [Thread-4] DEBUG org.apache.http.wire - http-outgoing-1 >> "[0xbf]jStreamNamex[0x1c]ads-publisher-changelog-test[0xff]"
        10:57:36.510 [Thread-4] DEBUG org.apache.http.wire - http-outgoing-1 << "HTTP/1.0 404 Not Found[\r][\n]"
        10:57:36.510 [Thread-4] DEBUG org.apache.http.wire - http-outgoing-1 << "Server: BaseHTTP/0.3 Python/2.7.13[\r][\n]"
        10:57:36.510 [Thread-4] DEBUG org.apache.http.wire - http-outgoing-1 << "Date: Tue, 02 May 2017 23:01:54 GMT[\r][\n]"
        10:57:36.510 [Thread-4] DEBUG org.apache.http.wire - http-outgoing-1 << "x-amzn-RequestId: 560c5d60-2f8b-11e7-b587-3f8e4fa4ca65[\r][\n]"
        10:57:36.510 [Thread-4] DEBUG org.apache.http.wire - http-outgoing-1 << "x-amz-id-2: VYdj2DMRvRD5I7DJymuoADReh4psixVlM0AdP3WXSAsfo+1FoYS/+wVYGyOLFzDKoxKSmVtSKqxWTPpU5ooBPAWAUPzROeJP[\r][\n]"
        10:57:36.510 [Thread-4] DEBUG org.apache.http.wire - http-outgoing-1 << "Content-Length: 29[\r][\n]"
        10:57:36.510 [Thread-4] DEBUG org.apache.http.wire - http-outgoing-1 << "Date: Tue, 02 May 2017 23:01:54 GMT[\r][\n]"
        10:57:36.510 [Thread-4] DEBUG org.apache.http.wire - http-outgoing-1 << "Connection: keep-alive[\r][\n]"
        10:57:36.510 [Thread-4] DEBUG org.apache.http.wire - http-outgoing-1 << "[\r][\n]"
        10:57:36.510 [Thread-4] DEBUG org.apache.http.wire - http-outgoing-1 << "<UnknownOperationException/>[\n]"
        10:57:36.510 [Thread-4] DEBUG org.apache.http.headers - http-outgoing-1 << HTTP/1.0 404 Not Found
        10:57:36.510 [Thread-4] DEBUG org.apache.http.headers - http-outgoing-1 << Server: BaseHTTP/0.3 Python/2.7.13
        10:57:36.511 [Thread-4] DEBUG org.apache.http.headers - http-outgoing-1 << Date: Tue, 02 May 2017 23:01:54 GMT
        10:57:36.511 [Thread-4] DEBUG org.apache.http.headers - http-outgoing-1 << x-amzn-RequestId: 560c5d60-2f8b-11e7-b587-3f8e4fa4ca65
        10:57:36.511 [Thread-4] DEBUG org.apache.http.headers - http-outgoing-1 << x-amz-id-2: VYdj2DMRvRD5I7DJymuoADReh4psixVlM0AdP3WXSAsfo+1FoYS/+wVYGyOLFzDKoxKSmVtSKqxWTPpU5ooBPAWAUPzROeJP
        10:57:36.511 [Thread-4] DEBUG org.apache.http.headers - http-outgoing-1 << Content-Length: 29
        10:57:36.511 [Thread-4] DEBUG org.apache.http.headers - http-outgoing-1 << Date: Tue, 02 May 2017 23:01:54 GMT
        10:57:36.511 [Thread-4] DEBUG org.apache.http.headers - http-outgoing-1 << Connection: keep-alive
        10:57:36.511 [Thread-4] DEBUG o.a.h.impl.execchain.MainClientExec - Connection can be kept alive for 60000 MILLISECONDS
        10:57:36.511 [Thread-4] DEBUG o.a.h.i.c.PoolingHttpClientConnectionManager - Connection [id: 1][route: {}->http://localhost:4568] can be kept alive for 60.0 seconds
        10:57:36.511 [Thread-4] DEBUG o.a.h.i.c.PoolingHttpClientConnectionManager - Connection released: [id: 1][route: {}->http://localhost:4568][total kept alive: 1; route allocated: 1 of 50; total allocated: 1 of 50]
        10:57:36.517 [Thread-4] INFO  c.a.protocol.json.JsonContent - Unable to parse HTTP response content
        com.fasterxml.jackson.core.JsonParseException: Invalid CBOR value token (first byte): 0x3c
         at [Source: [B@47a80916; line: -1, column: 1]

**Simple stack trace:**
`10:57:36.521 [Thread-4] DEBUG com.amazonaws.request - Received error response: com.amazonaws.services.kinesis.model.AmazonKinesisException: null (Service: AmazonKinesis; Status Code: 404; Error Code: null; Request ID: 560c5d60-2f8b-11e7-b587-3f8e4fa4ca65)
    10:57:36.521 [Thread-4] ERROR c.a.s.k.c.lib.worker.ShardSyncTask - Caught exception while sync'ing Kinesis shards and leases
    com.amazonaws.services.kinesis.model.AmazonKinesisException: null (Service: AmazonKinesis; Status Code: 404; Error Code: null; Request ID: 560c5d60-2f8b-11e7-b587-3f8e4fa4ca65)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1588) ~[aws-java-sdk-core-1.11.115.jar:na]
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1258) ~[aws-java-sdk-core-1.11.115.jar:na]
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1030) ~[aws-java-sdk-core-1.11.115.jar:na]
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:742) ~[aws-java-sdk-core-1.11.115.jar:na]
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:716) ~[aws-java-sdk-core-1.11.115.jar:na]
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699) ~[aws-java-sdk-core-1.11.115.jar:na]
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667) ~[aws-java-sdk-core-1.11.115.jar:na]
        at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649) ~[aws-java-sdk-core-1.11.115.jar:na]
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513) ~[aws-java-sdk-core-1.11.115.jar:na]
        at com.amazonaws.services.kinesis.AmazonKinesisClient.doInvoke(AmazonKinesisClient.java:1948) ~[aws-java-sdk-kinesis-1.11.115.jar:na]
        at com.amazonaws.services.kinesis.AmazonKinesisClient.invoke(AmazonKinesisClient.java:1924) ~[aws-java-sdk-kinesis-1.11.115.jar:na]
        at com.amazonaws.services.kinesis.AmazonKinesisClient.executeDescribeStream(AmazonKinesisClient.java:720) ~[aws-java-sdk-kinesis-1.11.115.jar:na]
        at com.amazonaws.services.kinesis.AmazonKinesisClient.describeStream(AmazonKinesisClient.java:696) ~[aws-java-sdk-kinesis-1.11.115.jar:na]
        at com.amazonaws.services.kinesis.clientlibrary.proxies.KinesisProxy.getStreamInfo(KinesisProxy.java:181) ~[amazon-kinesis-client-1.7.5.jar:na]
        at com.amazonaws.services.kinesis.clientlibrary.proxies.KinesisProxy.getShardList(KinesisProxy.java:243) ~[amazon-kinesis-client-1.7.5.jar:na]
        at com.amazonaws.services.kinesis.clientlibrary.lib.worker.ShardSyncer.getShardList(ShardSyncer.java:288) ~[amazon-kinesis-client-1.7.5.jar:na]
        at com.amazonaws.services.kinesis.clientlibrary.lib.worker.ShardSyncer.syncShardLeases(ShardSyncer.java:112) ~[amazon-kinesis-client-1.7.5.jar:na]
        at com.amazonaws.services.kinesis.clientlibrary.lib.worker.ShardSyncer.checkAndCreateLeasesForNewShards(ShardSyncer.java:88) ~[amazon-kinesis-client-1.7.5.jar:na]
        at com.amazonaws.services.kinesis.clientlibrary.lib.worker.ShardSyncTask.call(ShardSyncTask.java:68) ~[amazon-kinesis-client-1.7.5.jar:na]
        at com.amazonaws.services.kinesis.clientlibrary.lib.worker.MetricsCollectingTaskDecorator.call(MetricsCollectingTaskDecorator.java:49) [amazon-kinesis-client-1.7.5.jar:na]
        at com.amazonaws.services.kinesis.clientlibrary.lib.worker.Worker.initialize(Worker.java:427) [amazon-kinesis-client-1.7.5.jar:na]
        at com.amazonaws.services.kinesis.clientlibrary.lib.worker.Worker.run(Worker.java:356) [amazon-kinesis-client-1.7.5.jar:na]
`

**Detailed trace:**
`10:57:36.517 [Thread-4] INFO  c.a.protocol.json.JsonContent - Unable to parse HTTP response content
    com.fasterxml.jackson.core.JsonParseException: Invalid CBOR value token (first byte): 0x3c
     at [Source: [B@47a80916; line: -1, column: 1]
        at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1702) ~[jackson-core-2.8.4.jar:2.8.4]
        at com.fasterxml.jackson.dataformat.cbor.CBORParser._invalidToken(CBORParser.java:3052) ~[jackson-dataformat-cbor-2.8.4.jar:2.8.4]
        at com.fasterxml.jackson.dataformat.cbor.CBORParser.nextToken(CBORParser.java:709) ~[jackson-dataformat-cbor-2.8.4.jar:2.8.4]
        at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3834) ~[jackson-databind-2.8.4.jar:2.8.4]
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3783) ~[jackson-databind-2.8.4.jar:2.8.4]
        at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:2404) ~[jackson-databind-2.8.4.jar:2.8.4]
        at com.amazonaws.protocol.json.JsonContent.parseJsonContent(JsonContent.java:72) [aws-java-sdk-core-1.11.115.jar:na]
        at com.amazonaws.protocol.json.JsonContent.<init>(JsonContent.java:64) [aws-java-sdk-core-1.11.115.jar:na]
        at com.amazonaws.protocol.json.JsonContent.createJsonContent(JsonContent.java:54) [aws-java-sdk-core-1.11.115.jar:na]
        at com.amazonaws.http.JsonErrorResponseHandler.handle(JsonErrorResponseHandler.java:61) [aws-java-sdk-core-1.11.115.jar:na]
        at com.amazonaws.http.JsonErrorResponseHandler.handle(JsonErrorResponseHandler.java:33) [aws-java-sdk-core-1.11.115.jar:na]
        at com.amazonaws.http.AwsErrorResponseHandler.handleAse(AwsErrorResponseHandler.java:50) [aws-java-sdk-core-1.11.115.jar:na]
        at com.amazonaws.http.AwsErrorResponseHandler.handle(AwsErrorResponseHandler.java:38) [aws-java-sdk-core-1.11.115.jar:na]
        at com.amazonaws.http.AwsErrorResponseHandler.handle(AwsErrorResponseHandler.java:24) [aws-java-sdk-core-1.11.115.jar:na]
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1570) [aws-java-sdk-core-1.11.115.jar:na]
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1258) [aws-java-sdk-core-1.11.115.jar:na]
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1030) [aws-java-sdk-core-1.11.115.jar:na]
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:742) [aws-java-sdk-core-1.11.115.jar:na]
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:716) [aws-java-sdk-core-1.11.115.jar:na]
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699) [aws-java-sdk-core-1.11.115.jar:na]
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667) [aws-java-sdk-core-1.11.115.jar:na]
        at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649) [aws-java-sdk-core-1.11.115.jar:na]
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513) [aws-java-sdk-core-1.11.115.jar:na]
        at com.amazonaws.services.kinesis.AmazonKinesisClient.doInvoke(AmazonKinesisClient.java:1948) [aws-java-sdk-kinesis-1.11.115.jar:na]
        at com.amazonaws.services.kinesis.AmazonKinesisClient.invoke(AmazonKinesisClient.java:1924) [aws-java-sdk-kinesis-1.11.115.jar:na]
        at com.amazonaws.services.kinesis.AmazonKinesisClient.executeDescribeStream(AmazonKinesisClient.java:720) [aws-java-sdk-kinesis-1.11.115.jar:na]
        at com.amazonaws.services.kinesis.AmazonKinesisClient.describeStream(AmazonKinesisClient.java:696) [aws-java-sdk-kinesis-1.11.115.jar:na]
        at com.amazonaws.services.kinesis.clientlibrary.proxies.KinesisProxy.getStreamInfo(KinesisProxy.java:181) [amazon-kinesis-client-1.7.5.jar:na]
        at com.amazonaws.services.kinesis.clientlibrary.proxies.KinesisProxy.getShardList(KinesisProxy.java:243) [amazon-kinesis-client-1.7.5.jar:na]
        at com.amazonaws.services.kinesis.clientlibrary.lib.worker.ShardSyncer.getShardList(ShardSyncer.java:288) [amazon-kinesis-client-1.7.5.jar:na]
        at com.amazonaws.services.kinesis.clientlibrary.lib.worker.ShardSyncer.syncShardLeases(ShardSyncer.java:112) [amazon-kinesis-client-1.7.5.jar:na]
        at com.amazonaws.services.kinesis.clientlibrary.lib.worker.ShardSyncer.checkAndCreateLeasesForNewShards(ShardSyncer.java:88) [amazon-kinesis-client-1.7.5.jar:na]
        at com.amazonaws.services.kinesis.clientlibrary.lib.worker.ShardSyncTask.call(ShardSyncTask.java:68) [amazon-kinesis-client-1.7.5.jar:na]
        at com.amazonaws.services.kinesis.clientlibrary.lib.worker.MetricsCollectingTaskDecorator.call(MetricsCollectingTaskDecorator.java:49) [amazon-kinesis-client-1.7.5.jar:na]
        at com.amazonaws.services.kinesis.clientlibrary.lib.worker.Worker.initialize(Worker.java:427) [amazon-kinesis-client-1.7.5.jar:na]
        at com.amazonaws.services.kinesis.clientlibrary.lib.worker.Worker.run(Worker.java:356) [amazon-kinesis-client-1.7.5.jar:na]
        at com.schibsted.spt.advertising.kinesis.testUtils.ConsumerUtil$$anon$1.run(ConsumerUtil.scala:18) [shared-kinesis-test_2.11-10.0.1.jar:10.0.1]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_121]`

**Comment by whummer** [comment]
Thanks for the report. This seems to be related to the CBOR protocol (http://cbor.io/) which is currently not supported in *LocalStack* and the underlying Kinesis mock implementation (kinesalite).

You can set the environment variable `AWS_CBOR_DISABLE` in your tests, which causes the Kinesis client to fall back to JSON instead of CBOR. See here for an example how to do this from within Java (alternatively, you can set `AWS_CBOR_DISABLE=1` in the shell that executes your Java process):  https://github.com/atlassian/localstack/blob/master/ext/java/src/test/java/com/atlassian/localstack/TestRunnerTest.java#L32

**Comment by msumner91** [comment]
@whummer Thanks for the pointer - I'll give this a try now & let you know how it goes

**Comment by msumner91** [comment]
@whummer This has resolved the issue - thanks for your help!
