### ISSUE TITLE
SNS: Unable to publish to platform application endpoint

### ISSUE THREAD

**Issue by dhaspden** [atlassian/localstack#89]
**Steps to reproduce:**

```
docker run -e "SERVICES=s3,sns" -it -p 4567-4580:4567-4580 -p 8080:8080 atlassianlabs/localstack
aws --endpoint-url=http://192.168.99.100:4575 sns publish --target-arn arn:aws:sns:us-east-1:123456789012:endpoint/GCM/application/9b3cd652-cee2-4ce1-b743-906957fca470 --message "Hello, world"
```

Tried with and without a platform application created and both times received the same stack trace, below.

```
/usr/lib/python2.7/site-packages/supervisor/options.py:296: UserWarning: Supervisord is running as root and it is searching for its configuration file in default locations (including its current working directory); you probably want to specify a "-c" argument specifying an absolute path to a configuration file for improved security.
  'Supervisord is running as root and it is searching '
2017-05-03 15:35:46,565 CRIT Supervisor running as root (no user in config file)
2017-05-03 15:35:46,566 INFO supervisord started with pid 1
2017-05-03 15:35:47,569 INFO spawned: 'dashboard' with pid 7
2017-05-03 15:35:47,570 INFO spawned: 'infra' with pid 8
. .venv/bin/activate; exec localstack/mock/infra.py
(. .venv/bin/activate; bin/localstack web --port=8080)
Starting local dev environment. CTRL-C to quit.
 * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
 * Restarting with stat
Starting mock S3 (port 4572)...
Starting mock SNS (port 4575)...
 * Debugger is active!
 * Debugger PIN: 621-594-402
2017-05-03 15:35:49,456 INFO success: dashboard entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2017-05-03 15:35:49,456 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Ready.
ERROR:localstack.mock.generic_proxy:Error forwarding request: None
Traceback (most recent call last):
  File "/opt/code/localstack/localstack/mock/generic_proxy.py", line 92, in forward
    data=data, headers=self.headers, return_forward_info=True)
  File "/opt/code/localstack/localstack/mock/proxy/sns_listener.py", line 32, in update_sns
    for subscriber in SNS_SUBSCRIPTIONS[topic_arn]:
KeyError: None
ERROR:localstack.mock.generic_proxy:Error forwarding request: None
Traceback (most recent call last):
  File "/opt/code/localstack/localstack/mock/generic_proxy.py", line 92, in forward
    data=data, headers=self.headers, return_forward_info=True)
  File "/opt/code/localstack/localstack/mock/proxy/sns_listener.py", line 32, in update_sns
    for subscriber in SNS_SUBSCRIPTIONS[topic_arn]:
KeyError: None
ERROR:localstack.mock.generic_proxy:Error forwarding request: None
Traceback (most recent call last):
  File "/opt/code/localstack/localstack/mock/generic_proxy.py", line 92, in forward
    data=data, headers=self.headers, return_forward_info=True)
  File "/opt/code/localstack/localstack/mock/proxy/sns_listener.py", line 32, in update_sns
    for subscriber in SNS_SUBSCRIPTIONS[topic_arn]:
KeyError: None
ERROR:localstack.mock.generic_proxy:Error forwarding request: None
Traceback (most recent call last):
  File "/opt/code/localstack/localstack/mock/generic_proxy.py", line 92, in forward
    data=data, headers=self.headers, return_forward_info=True)
  File "/opt/code/localstack/localstack/mock/proxy/sns_listener.py", line 32, in update_sns
    for subscriber in SNS_SUBSCRIPTIONS[topic_arn]:
KeyError: None
ERROR:localstack.mock.generic_proxy:Error forwarding request: None
Traceback (most recent call last):
  File "/opt/code/localstack/localstack/mock/generic_proxy.py", line 92, in forward
    data=data, headers=self.headers, return_forward_info=True)
  File "/opt/code/localstack/localstack/mock/proxy/sns_listener.py", line 32, in update_sns
    for subscriber in SNS_SUBSCRIPTIONS[topic_arn]:
KeyError: None
```

This is using the latest docker image as of today.  Any suggestions?  For the record creating a new platform application worked.  I am running OSX Sierra on a Mac Pro if that makes a difference.

**Comment by whummer** [comment]
@dhaspden Apologies for the delay, this has already been fixed a while ago (see this commit: https://github.com/atlassian/localstack/commit/482d3508812b60c3b52ae54b267a0d1617b39bbc#diff-c74025a1536118c1102a44d3c943fb44R17 ) Can you please pull the latest Docker image and give it a try? Thanks

**Comment by dhaspden** [comment]
@whummer That seems to have done the trick.  I have a suspicion that will clear out some of the other python errors I have come across too.  I will let you know if anything else comes up.  Thank you!
